### ISSUE TITLE
Add fiat currency conversion for CZK

### ISSUE THREAD

**Issue by zikziko** [ACINQ/phoenix#100]
Hi,
it would be nice to have an option to select CZK as local fiat currency in phoenix wallet so that more people are comfortable with using the wallet.

**Comment by taxmeifyoucan** [comment]
+1 
Lot of new users from Czechia are being onboarded via fiat to lightning and CZK:SATS rate would be perfect. There are many fiat currencies in the app but CZK is missing. API doesn't provide it?

**Comment by dpad85** [comment]
Hi, the current APIs we use do not provide this exchange rate, but coindesk API does: https://api.coindesk.com/v1/bpi/currentprice/CZK.json
