### ISSUE TITLE
Add fiat currency conversion for ILS

### ISSUE THREAD

**Issue by Sorikal** [ACINQ/phoenix#101]
I would appreciate support for my local currency, ILS (Israel Shekels).

**Comment by dpad85** [comment]
Just like #100 we can use the Coindesk API to retrieve the ILS/BTC exchange rate: https://api.coindesk.com/v1/bpi/currentprice/ILS.json

**Comment by maxwalts** [comment]
I'd like to make a PR for this issue. I'm new to this project and PRs in general, so could someone help me by providing the path where currency conversions are handled?

**Comment by robbiehanson** [comment]
Support for ILS has been implemented in shared KMP library, and will be available in next iOS release.

<img height="450" alt="Screen Shot 2021-11-10 at 09 33 22" src="https://user-images.githubusercontent.com/304604/141142918-1400758c-045d-4f0d-b567-c8d88230e121.png">

**Comment by robbiehanson** [comment]
Support for ILS (and hundreds of other fiat currencies) has been implemented in a shared layer, written in Kotlin Multiplatform. We are in the process of migrating the Android app to use this new cross-platform library, at which point support for pretty much every fiat currency will be available on Android (like it currently is on iOS).
