### ISSUE TITLE
Tx stuck at "processing"

### ISSUE THREAD

**Issue by ArbenKarb** [ACINQ/phoenix#102]
Tried to settle a BTCPayServer invoice with phoenix. Payment didn't go through and tx is stuck at "processing", while payment amoung was deducted from balance

**Comment by dpad85** [comment]
A payment gets stuck in a pending state when there is an unresponsive node somewhere in the payment route. After a while the payment will fail, and you will get your funds back, but in the meantime, you have to wait. This delay is dynamic and depends on the route taken.

Node operators will avoid connecting to notoriously unreliable nodes, but still it can happen. Note that the faulty node here could be a relaying node, or even the receiving BTCPayServer node.
