### ISSUE TITLE
Swap to onchain problems

### ISSUE THREAD

**Issue by stefanwouldgo** [ACINQ/phoenix#11]
Yesterday I tried to pay someone to a bitcoin address with phoenix (to BRD wallet). First of all, the QR code doesn't get recognized at all when it contains a payment amount.

When we left out the payment amount, the QR code worked, but the swapping process stalled. I aborted after a few minutes, tried again and aborted again. Might have been a problem with the swap provider service or even the Internet connection at the coffee shop. 

Otherwise, congratulations on pioneering a fantastic UX!

**Comment by t-bast** [comment]
Thanks for the report. Could you share your application logs privately?
For example by DM on our Gitter or email.
Don't hesitate to anonymize if there's confidential data in there (onion addresses for example).

**Comment by dpad85** [comment]
Regarding the unrecognized QR code from Bread Wallet, it's a bug on their iOS version where for some locales the amount in the bitcoin URI would use a `,` char as decimal separator, which is not BIP-21 compliant, and so Phoenix must reject the invoice.

For the stalled swapping, it's typical of a lost connection with the remote peer handling the swap. This is a general problem that affect several features (eg pay-to-open) and that should be fixed soon.
