### ISSUE TITLE
Receiving payments in emulator

### ISSUE THREAD

**Issue by pavoltravnik** [ACINQ/phoenix#114]
I am using Android studio emulator with Android 10. Downloaded latest apk from releases 1.4.0
I am able to get on chain payment. I am able also send satoshis through LN. However I am unable to receive satoshis to Phoenix wallet because of problem with routing. `Automaticly accept chanell opening` is enabled. Status of connection is fine.

<img width="427" alt="Screenshot 2020-11-11 at 08 59 55" src="https://user-images.githubusercontent.com/21983609/98785138-6fd6a200-23fc-11eb-8170-e534cfb1bb37.png">
<img width="435" alt="Screenshot 2020-11-11 at 08 59 27" src="https://user-images.githubusercontent.com/21983609/98785151-736a2900-23fc-11eb-80e5-1ccb4026ef70.png">
<img width="435" alt="Screenshot 2020-11-11 at 09 01 44" src="https://user-images.githubusercontent.com/21983609/98785305-b0ceb680-23fc-11eb-9745-cea965a7530c.png">

**Comment by dpad85** [comment]
> However I am unable to receive satoshis to Phoenix wallet because of problem with routing.

What wallet/node are you sending from? Could you share the `payment hash` of the payment that you cannot receive (email to phoenix@acinq.co if you prefer)? The issue could be on the sender side.

The recent on-chain fee spike has an effect on the available inbound capacity of channels. It can be noticeable on your ability to receive payments if you only have small channels (under 100k sat).

**Comment by pavoltravnik** [comment]
I am closing this issue, payment worked now. I used multiple wallets so it had to be related to  inbound capacity of channels. Thanks a lot.
