### ISSUE TITLE
Connecting to peer

### ISSUE THREAD

**Issue by flashtheman** [ACINQ/phoenix#124]
I'm currently testing Phoenix wallet and was not able to do payments to the following parties:

1. https://yalls.org/coffee/

2. https://tippin.me/help-tippin

Phoenix just showed "Connecting to peer" forever.

**Comment by dpad85** [comment]
`Connecting to peer` means that your app is not able to connect to the ACINQ node (the peer for your channels) and as such the wallet is not able to send any payments. This is not related to those two websites you mention, but to your device's connection.

- what version of Phoenix are you running? you can see that in Settings > About (top section)
- are you using WiFi?
- are you using a VPN?

**Comment by flashtheman** [comment]
Thanks for your response. I just tried it again with yalls and it worked now. I'm pretty sure I had an internet connection when I tried yesterday but I can't guarantee it.

The version I used was 1.4.4 (19)

Maybe it makes sense to implement some kind of timeout which then tells you to check your internet connection?

**Comment by flashtheman** [comment]
I must say the experience of paying with phoenix is incredible (now that it works). I'm totally fascinated.

**Comment by dpad85** [comment]
> Maybe it makes sense to implement some kind of timeout which then tells you to check your internet connection?

That's not a bad idea. The app already displays a blinking "Connecting..." message in the home screen top-left corner, but having some kind of popup/notification could be useful.
