### ISSUE TITLE
"No payment found"

### ISSUE THREAD

**Issue by Steffen-8** [ACINQ/phoenix#13]
I have sent some sats to a new wallet. When trying to sent 1/some/all of them back I either get the error message "No payment found" or no error message at all and just a return to the previous screen. In any case no sending has happened.

When I try to sent more to this wallet I get an error message on the sending wallet (a Phoenix wallet on a different smartphone) telling me "Payment failed. No money has been sent." and "incorrect payment details or unknown payment hash".

I have no idea how to use the new wallet. Money is just stuck there (very small amount). I can not add more and not sent anything back.

**Comment by dpad85** [comment]
Hello, can you provide your node id? You can find that in the Settings page > Channels list.

**Comment by Steffen-8** [comment]
Here is the node id for the wallet giving the "No payment found" error message: 0399a96b3caa5709bffd172e5e945d1abc660b7b25efc58035008e63abb245d7fb

**Comment by dpad85** [comment]
Can you try again and make sure that the receiving app is online, and is in foreground?

**Comment by Steffen-8** [comment]
The handling of the two phones almost guarantees that both wallets are always in the foreground. I tried again to send 5 sats explicitly making sure that both apps are in foreground. I still get the same error message "No payment found".

**Comment by Steffen-8** [comment]
The error message itself ("No payment found") makes no sense for an end user of the wallet. It feels like it points to an internal inconsistency. Better to point this out in the error message, e.g. "Oops, there was a bug. Please send a report by ...!"

**Comment by Steffen-8** [comment]
I tried it with another Android device and it is easily reproducible. Install the Phoenix app. Receive, e.g. 2 sats from another device (with a Phoenix app). This works. Try to send e.g. 1 sat back. You get the error message.

**Comment by t-bast** [comment]
This issue has been fixed a while ago. Please re-open if you're still experiencing this.
