### ISSUE TITLE
Send transaction "Pending" with funds withdrawn

### ISSUE THREAD

**Issue by blankscreengithub** [ACINQ/phoenix#135]
I sent a payment to a Muun invoice. The Muun wallet said the transaction failed. My Phoenix wallet indicates "Pending" and the funds were withdrawn from the wallet.

I saw on closed issue #102 there is an unresponsive node along the payment route and my funds will be returned and the delay time varies. It has been 12 hours and the funds have not returned yet. Does anyone have any experience with this issue and how long it took funds to return to Phoenix wallet? Could it take longer like a week or more?

**Comment by blankscreengithub** [comment]
Update: it took about 22 hours for the funds to be returned.

**Comment by t-bast** [comment]
This is a known issue with Muun, we cannot do anything about it.
The payment stays stuck at the Muun node and we need to wait for them to fail it.
@esneider do you have an ETA for when this will be fixed?

**Comment by esneider** [comment]
Hey @t-bast, thanks for the ping. I'll check what's going on and get back to you.
