### ISSUE TITLE
Support for webln / makeInvoice

### ISSUE THREAD

**Issue by jk14** [ACINQ/phoenix#137]
Phoenix Wallet is focused on providing as easy interacting with Lightning Network as possible. In such case - the webln support is simply "no brainer" option for Phoenix. It allows to request invoices with a specific amount from the user, who only click 'OK' on already prepared LN invoice. This makes LN payment process ultimately smooth & easy from the user perspective. It also allows for strict integration with surrounding Lightning Network services (like: topping-up the Phoenix Wallet from One-Click Miner with a single click)

The webln documentation:
https://github.com/joule-labs/webln
https://webln.dev/#/
https://webln.dev/#/api/make-invoice

P.S. this functionality is already supported by e.g. BlueWallet and Breez:
https://github.com/breez/breezmobile/commit/3315717fb1f001d383cf985ec8a0e7fd3e8e5c62
https://github.com/breez/breezmobile/commit/9f90a951c39688d6e34f703e6175ac9137d5add0

**Comment by t-bast** [comment]
This is not a standardized protocol, so to be honest it's unlikely we'll integrate it in the short term.
We don't want to rush to add tons of stuff to Phoenix that we then need to maintain and provide support for if we're not building on stable protocols or standards.

**Comment by t-bast** [comment]
But we've integrated some LN-url parts and plan to integrate more of them, that may give you what you need.

**Comment by jk14** [comment]
I will try to achieve this functionality with LNURL
