### ISSUE TITLE
"No payment found" error

### ISSUE THREAD

**Issue by philbertw4** [ACINQ/phoenix#15]
This might be related to #13 (same error message), but opening a separate issue since I'm not quite sure. 

For me, steps to reproduce (as of moments ago, and after trying multiple times with different invoices):
1. opened chrome browser from android phone and visited https://pollofeed.com and generated invoice
2. pasted invoice into phoenix
3. got "No Payment found" error with no other description

A few days ago, I was still unable to pay PolloFeed but was getting a different error: "incorrect payment details or unknown payment hash." Whereas now, the error seems to have switched to this "No payment found" error at least when trying to pay PolloFeed.

When trying to pay some other sites (such as, for example, an invoice generated by the telegram bot `@lntxbot`), I am now getting the "incorrect payment details or unknown payment hash" error. Whereas before, I had successfully been able to pay with Phoenix.

Hope this helps with some debugging. Let me know if there is more information you need.

P.S. Nice work on Phoenix!! Once these kinks are worked out, it will be a fantastic user experience!

**Comment by dpad85** [comment]
Hello, thanks for reporting this issue. I reckon this is the same as #13. Can you provide your node id? You can find that in the Settings page > Channels list.

**Comment by philbertw4** [comment]
Thanks. Node id sent privately via gitter to you.

**Comment by dpad85** [comment]
The problem comes from an issue in the relaying node (ACINQ node here), which basically expects a direct channel to the final node when relaying a payment to this final node, if this node claims support for multipart payment. This issue will be fixed with https://github.com/ACINQ/eclair/pull/1253
