### ISSUE TITLE
Payment Failed. No Money has been sent.

### ISSUE THREAD

**Issue by Yerontour** [ACINQ/phoenix#16]
Get a 'incorrect payment details or unknown payment hash' error. 

I have 4 channels open and the other party just downloaded the Phoenix wallet with 0 open channels. Tried with 1000 Satoshi and with 75000 Satoshi.

**Comment by dpad85** [comment]
Hello,

Can you make sure that your counterpart is online when sending the payment, and that his wallet is in foreground?

**Comment by dpad85** [comment]
It's probably the same issue as #15 and #13

**Comment by Yerontour** [comment]
Yes, on foreground it works now. 

Thanx, love Phoenix....keep up the good work  👍
