### ISSUE TITLE
Old versions used in Dockerfile (base image, maven, cmake, sdk/ndk tools, etc..)

### ISSUE THREAD

**Issue by emanuelb** [ACINQ/phoenix#165]
1. Old base Ubuntu 20.10 used which is EOL.
https://github.com/ACINQ/phoenix/blob/67e5a9754d92dc58d3082afa42e4918049244b05/Dockerfile#L33

Ubuntu 20.10 is EOL in: July, 2021
Use 21.04 instead.

2. Old base `adoptopenjdk/openjdk11:jdk-11.0.8_10-alpine`

https://github.com/ACINQ/phoenix/blob/67e5a9754d92dc58d3082afa42e4918049244b05/Dockerfile#L2

latest version is: `jdk-11.0.11_9-alpine`
There also slim version which is better to use if possible: `jdk-11.0.11_9-alpine-slim`

3. Old Maven version 3.6.3

https://github.com/ACINQ/phoenix/blob/67e5a9754d92dc58d3082afa42e4918049244b05/Dockerfile#L8

latest version of maven is: 3.8.1

4. Old SDK tools:

https://github.com/ACINQ/phoenix/blob/67e5a9754d92dc58d3082afa42e4918049244b05/Dockerfile#L38-L39

The code need to be changed as link changed to name `commandlinetools-linux`:
https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
from: 
https://developer.android.com/studio/index.html#command-tools

5. Old Cmake

https://github.com/ACINQ/phoenix/blob/67e5a9754d92dc58d3082afa42e4918049244b05/Dockerfile#L43

newest from android sdk tools: 3.18.1

6. Old BuildTools

https://github.com/ACINQ/phoenix/blob/67e5a9754d92dc58d3082afa42e4918049244b05/Dockerfile#L41

newest version is: 31.0.0

7. Old NDK:

https://github.com/ACINQ/phoenix/blob/67e5a9754d92dc58d3082afa42e4918049244b05/Dockerfile#L42

https://developer.android.com/ndk/downloads

Latest LTS Version: 21.4.7075529
Latest Stable Version: 22.1.7171670

**Comment by t-bast** [comment]
We've been working on migrating Phoenix to a completely new stack based on Kotlin multi-platform:

- https://github.com/acinq/lightning-kmp
- https://github.com/acinq/phoenix-kmm

Any work on deterministic builds will be done over there.

**Comment by dpad85** [comment]
Fixed with https://github.com/ACINQ/phoenix/commit/0ff688fc014cc94806daca93799821777c456e7f

Note that this repo is the main repository again, the phoenix-kmm one is deprecated.
