### ISSUE TITLE
issue with nano/pico denomination?

### ISSUE THREAD

**Issue by nicolasburtey** [ACINQ/phoenix#168]
we're trying to reproduce a bug we have parsing Phoenix invoice. is there a difference between iOs and Android?

More context here: https://github.com/GaloyMoney/galoy-mobile/issues/114

**Comment by dpad85** [comment]
The Android and iOS app currently use different LN library and invoice will not be generated the same way. In the twitter post reporting the issue, the user was on iOS.

This is an invoice generated from Phoenix iOS, for 3089044 millisatoshi (around 1USD):

```
lnbc30890440p1ps0uuh8pp5pjdctpnhnz6t2etvfqplmcgzcpt3wutx0077xz3w46jf90uy77aqdqqcqpjsp57gst9s0dsxv3lq59gla6tzmr58tvdfu2ued0ty0p03szjmlqfruq9qtzqqqqqqysgqxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glclllzk7a72vf87qqqqqlgqqqqqeqqjqyl99rwc7fscma2wwdf0r7lfcnnz3ryuafcg3e30r58g93tu47rwnvyh9v2rg6xgutyl2qxdx07mawf9aj526nl2mwysp34g5clna5ccqkguqrk 
```

**Comment by robbiehanson** [comment]
The comment I left in your issue (copied here):

>You can reproduce this on Phoenix iOS by typing in an amount such as "0.01 sat". In the real world it is more likely that the user will enter an amount in fiat, and the conversion will result in an amount such as "12,345.01 sat". Either of these amounts currently result an invoice that uses pico.
>
> The code that determines the unit used in the lightning invoice is [here](https://github.com/ACINQ/lightning-kmp/blob/326d1884b7c023a7051580d7682b8717c87eb22f/src/commonMain/kotlin/fr/acinq/lightning/payment/PaymentRequest.kt#L263)

**Comment by dpad85** [comment]
Closed this issue since the referenced issue has been closed too.
