### ISSUE TITLE
Swap-in Fees Subtracted Twice in TX History

### ISSUE THREAD

**Issue by GebertJung** [ACINQ/phoenix#170]
Device:
- iPhone 8
- iOS v14.6
- Phoenix v1.0.4

Steps taken:
- generate new wallet
- show bitcoin swap in address
- transfer .002BTC (excluding tx fee) to said address on chain

Result:
- balance shows: 197000sat
- tx history show: +194000sat

![4A764761-F006-4FFA-A149-0053A860F38F_1_105_c](https://user-images.githubusercontent.com/81487747/127906912-8abb5845-fbfb-4155-8252-54aad1b79a3b.jpeg)
![2C9F925C-CABC-4B57-9B1B-E6E483BE97E8_1_105_c](https://user-images.githubusercontent.com/81487747/127906943-e1d9d82a-18c6-4746-888b-9b904e8cda8c.jpeg)
![647B93FD-552E-42B4-8BCF-ABBBB703938A_1_105_c](https://user-images.githubusercontent.com/81487747/127906963-9a30d749-cd48-40f9-9a3a-da2ef161c01a.jpeg)

**Comment by robbiehanson** [comment]
Good timing! We were just discussing this bug internally, and we needed to create a GitHub issue for it. Thank you!

Technical note:
- the amount is incorrect for SwapIn (receiving via OnChain)
- but the amount is correct for PayToOpen (receiving amount via Lightning)

The 2 paths use opposite approaches when storing the `{amount=X, fees=Y}`
