### ISSUE TITLE
Deep Link Support

### ISSUE THREAD

**Issue by juscamarena** [ACINQ/phoenix#186]
It'd be nice to have deep link support, especially for iOS. Anyone with more than one lightning wallet on iOS has a hard time having the URI open the correct wallet...

Bluewallet and Muun seem to support deeplinking and it'd help the UX for wallets if Phoenix also supported this.

Examples:

https://bluewallet.io/testpage/#:~:text=Deeplinks%20prefixed,%60bluewallet%3A%60
bluewallet:bitcoin:BC1QH6TF004TY7Z7UN2V5NTU4MKF630545GVHS45U7?amount=666&label=Yo

bluewallet:lightning:lnbc10u1pwjqwkkpp5vlc3tttdzhpk9fwzkkue0sf2pumtza7qyw9vucxyyeh0yaqq66yqdq5f38z6mmwd3ujqar9wd6qcqzpgxq97zvuqrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwqz9hx5qqtmgqqqqqqqlgqqqqqqgqjq5duu3fs9xq9vn89qk3ezwpygecu4p3n69wm3tnl28rpgn2gmk5hjaznemw0gy32wrslpn3g24khcgnpua9q04fttm2y8pnhmhhc2gncplz0zde

**Comment by dpad85** [comment]
Thanks it seems like a good idea for iOS. @robbiehanson Wdyt?

**Comment by robbiehanson** [comment]
It's an excellent idea! We plan on implementing it soon.

**Comment by alescode** [comment]
Hey @robbiehanson! Just want to support the petition for this feature to be added soon. The experience on Bitrefill.com and other sites that allow bitcoin payments would be greatly improved for Phoenix users.

**Comment by robbiehanson** [comment]
@alescode Support for this has been added to the iOS version. (So you can use "phoenix:lightning:LNURL123...123") However, we're still working on adding it to the Android side.

**Comment by robbiehanson** [comment]
Android-specific issue: #251
