### ISSUE TITLE
Use larger, filled and, more lowered primary buttons

### ISSUE THREAD

**Issue by Bosch-0** [ACINQ/phoenix#197]
Currently primary buttons used in Phoenix are quite small and are presented in a more 'secondary' nature (being outlined). For a slightly smoother UX/UI I would recommend using larger, more lowered and filled buttons throughout. Lower buttons are easier to click for users who use larger devices and may not be as easily be able to reach the center of the screen. Below is an example from the first screen in on-boarding:

![image](https://user-images.githubusercontent.com/55287964/136804578-620c575e-a083-488a-ace4-c70adaf24a12.png)

**Comment by robbiehanson** [comment]
<img height="450" alt="Screen Shot 2022-04-14 at 16 49 13" src="https://user-images.githubusercontent.com/304604/163482315-18ae96bf-5261-48a6-b8f6-f2741db95b43.png">

Also incorporated [this](https://github.com/BitcoinDesign/Guide/issues/535) idea:

<img height="450" alt="Screen Shot 2022-04-14 at 16 49 40" src="https://user-images.githubusercontent.com/304604/163482423-612ac345-e93b-4a05-8b96-6cf2ab60358a.png">
