### ISSUE TITLE
Auto read clipboard in send screen

### ISSUE THREAD

**Issue by Bosch-0** [ACINQ/phoenix#200]
When opening the receive screen if the user has a Lightning invoice copied in their clipboard it should auto read it and give an option to click a button opening that invoice. 

Mockup below:

![image](https://user-images.githubusercontent.com/55287964/136814785-5bdc7f40-0f7d-4c89-a7f3-9997fadddd20.png)

**Comment by Bosch-0** [comment]
Here is a quick mockup integrating your suggestions:

- Icon on top right lets you pick an image. 
- Only show the payment amount and who it is being sent to. 
    - If they have a node alias set you could put this there or if they use an invoice name similar to what blixt does. Showing invoice data probably isn't required here. If they want to they have send see it within the next send details screen. 
    - If no name could just say 'to unknown.' 
- If clipboard is clear have option to manually enter, for Lnaddress for example.
    - May need to add a 'clear clipboard' button to the right of the clipboard popup which would switch to the manually enter screen. This would be if the user has something on their clipboard but wants to manually pay instead. 
- Also added other clipboard states for LNURL-Pay and LNURL-Withdraw on the left.

![image](https://user-images.githubusercontent.com/55287964/137432345-edbde267-afc1-43ec-8217-bffd059cf360.png)

**Comment by robbiehanson** [comment]
I started to implement this. But in testing I noticed something I hadn't considered before:

<img height="450" src="https://user-images.githubusercontent.com/304604/152034171-1fb54cff-2670-4fe2-90fe-6a368235010e.PNG">

On iOS, we can quietly ask **if** the clipboard has a string (yes or no). But if we actually **read** the string, then iOS presents this pop-up. I personally find it to be a little distracting.

(Note that it's quite common to have something in the clipboard - usually a string. So this pop-up will be occurring most of the time we visit this screen.)

Also, we probably shouldn't fetch a LNURL unless instructed to do so by the user. There are security considerations.

So, what we can discover (without performing a URL request):
- Bolt 11 invoice
- LNUrl.Auth
- LNUrl (generic URL)

Open questions for discussion:
- Does the iOS pop-up pose a problem ?
- Will the user care, or is this to be expected ?
- How will this feature be affected by Bolt 12 offers ?

**Comment by dpad85** [comment]
> Does the iOS pop-up pose a problem ?

If it does then the whole auto-read feature has to be dropped. By the way, recent versions of Android show the same warning.

It is not great, it does feel a bit invasive, but still seems OK to me. This behaviour would be limited to that screen, whose purpose is obvious (send a payment after reading external data) so the user can reasonably expect that the app will read the clipboard. We could make this auto-read feature opt-out ?

> How will this feature be affected by Bolt 12 offers ?

Bolt12 offers should be like classic Bolt11 invoices in that they can contain a description/amount that we can show the user before actually calling the offer itself.

**Comment by robbiehanson** [comment]
@Bosch-0 I really liked the clean simplicity of your mock-ups. Especially how there was just a single button at the bottom of the scan screen. So here's what I came up with.

![clipboard_inspect](https://user-images.githubusercontent.com/304604/161126709-2376d622-d500-4dbe-a36b-9023351d4ecc.gif)

**Comment by Bosch-0** [comment]
Hey Robbie, thanks!

Looks good! How does it appear if there is nothing on the clipboard? This prompt should probably only be shown if there is in fact relevant data on the clipboard. 

One visual improvement suggestion would be the hamburger menu, I think it's protruding a little too much into the main screen region. A possible cleaner solution could be to have a button in the bottom right (so its easily clickable by most people) that when clicked shows a paste, image and manual entry option. Similar to this menu on Samurai shown below

![Screenshot_20220401-105612](https://user-images.githubusercontent.com/55287964/161188820-84e7fa98-1d83-4ee4-9b92-11e5038b34de.png)

**Comment by robbiehanson** [comment]
Closed via PR #260
