### ISSUE TITLE
[UX/UI] Re-ordering of the navigation items in the `Settings` and unifying `backup`option

### ISSUE THREAD

**Issue by pavlenex** [ACINQ/phoenix#204]
Hey guys, on a recent call where we tested Phoenix UX from a perspective of a new user, we noticed that the `Settings` tab could use sligt refinement. 

Below are 2 concrete suggestions, that Bitcoin Design community has.

![136594670-e3c318f4-4eec-4307-944f-41345daa8676](https://user-images.githubusercontent.com/36959754/136860713-b2329df7-c658-4b7f-ab2f-a2cc5f03a7c4.png)

- [x] 1. Moving `Tor` and `Electrum` in `Advanced`

The options for Tor and Electrum seem like something a more technically advanced user may want to use. Our recommendation is to move those into an advanced tab if you guys feel it's suitable in order to free up space for more general settings.

- [x] 2. Unifying `Cloud backup` and `Recovery phrase` into `Backup`

In our Bitcoin Design Guide, we refer to the backups as [automatic cloud backup](https://bitcoin.design/guide/private-key-management/cloud-backup/) and [manual backup](https://bitcoin.design/guide/private-key-management/manual-backup/). Since on the first screen, Phoenix promts users to do a `backup` it may be good experience to have a screen where options for either automatic cloud backup or manual backup would be offered to the user who can be re-directed to this screen. That's why we'd like to recommend to have a unified `Backup` screen where you would offer these two options. Curios to hear if these two are different technically or recover different things, if so it may be good idea to have them separately. 

Would love to hear what you think about them and if you have some reasoning to do it differently or leave these the same.

**Comment by robbiehanson** [comment]
> Curious to hear if these two are different technically or recover different things, if so it may be good idea to have them separately.

Yes, there is a small technical difference. For cloud backup, we plan on supporting 2 things:

- backing up transactions (such as: "Sent 150,000 sats to Alice for Pizza")
- backing up the seed

These options are independent from one another, and can be enabled/disabled separately. For example, a user may wish to manually backup their seed, but allow Phoenix to backup their transaction history.

(PS - This makes sense from a security perspective too. When we backup transactions in the cloud, we encrypt them using a key that's derived from the seed.)

The logic behind your suggestion makes sense. Now we're just trying to understand how the "backup transactions" option fits into the mix.

**Comment by pavlenex** [comment]
@robbiehanson Thanks for partially addressing this one, and for clarifying the difference in backup options.

From what I understood, when you guys ask users to backup the seed, you indeed refer to the `seed option` (which backs up the channels and the on-chain wallet, correct?)

This is how I though of a menu hierarchy and perhaps and please correct me if I am wrong:

- Backup
   - Manual backup (backs up the seed, channels) 
   - Automatic cloud backup (backs up the seed, channels and transaction information)

**Comment by robbiehanson** [comment]
This is beautiful :heart_eyes:
Very well thought out !

**Comment by Bosch-0** [comment]
Happy to go further with this if this is something Phoenix is looking for currently :)

**Comment by robbiehanson** [comment]
See PR #229 for screenshots. PR has been merged, and should make its way into the next release.

**Comment by pavlenex** [comment]
Awesome to see @robbiehanson 🔥 

If I'm not mistaken, at least according to the screenshots this resolves https://github.com/ACINQ/phoenix/issues/205 as well?

**Comment by robbiehanson** [comment]
We like several of the choices you've made in the #205 designs, and we're going to be reviewing it soon. In particular, the "10,000 sat minimum for first payment" has been a continual pain point & source of confusion. So we would certainly like to make improvements in this area.

**Comment by dpad85** [comment]
After some testing, it turns out that unifying the backup option in a single screen does not work well.

Backing up the recovery phrase and backing up payments are in fact two different things. Mixing those two under a generic backup menu dilutes the importance of the recovery phrase.

So:
- Recovery phrase should be a top level entry in the main setting screen.
- Backing up the seed on iCloud should be a convenience option in this Recovery phrase screen. Disabled by default.
- Backing up payments should always be done when possible. Payments data are encrypted, there's no reason not to enable it. Some advanced users may want to tweak a few things but that should be hidden in some advanced menu.
