### ISSUE TITLE
[UX/UI] Link to backup on the home screen & progressive backup message 

### ISSUE THREAD

**Issue by pavlenex** [ACINQ/phoenix#205]
Hey guys, on a recent call we had a very interesting brainstorming about the error message displayed on the phoenix wallet home screen. Would love to hear your thoughts, if for any reason you don't agree with a suggestion, would love to hear some thoughts and feel free to close the issue.

![136593580-2dd71979-cc13-4649-adc6-a1f07dfe1584](https://user-images.githubusercontent.com/36959754/136861330-7a3106b4-a1e6-43a5-aede-ba2d69d354e3.png)

- [x] Link to the backup page from the backup warning 

Currently, when a user arrives to Phoenix wallet for the first time, they see a big scary message to do a backup. However, the user isn't instructed _how_ to do a backup. So our first recommendation would be to **link** to a backup page from that initial message. This recommendation would work well with that we've suggested in #204.

- [x] Progressive backup prompt 

This is something we'd like to get your thoughts on as you may have some reasoning against it.  In the Bitcoin Design guide, we recently added a recommendation that wallet could prompt users to perform a backup after the user has received bitcoin for the first time, since then they're financially incentivised to do a backup and if they have no btc it doesn't really make sense to backup an empty wallet. This is also recommended because usually the first transaction is usually a hand-holding process with a friend the proposed progressive message may reduce the stress and friction.

Our recommendation is to show the `backup` error message on the home page or in a form of a notification after the user has received the first payment.

**Comment by pavlenex** [comment]
Hey, posting a follow up with more context and examples on the `Progressive backup prompt`.

We came up to a conclusion that users who don't have any bitcoin in their wallet are not as much incentivised to do a backup. However, there's also a risk of asking a user after receiving the funds, so the idea @sbdesign is a good middle ground and proposes that we ask user to perform the backup right after the first payment. So that the `receiving a first payment` becomes a flow on it's own, a special flow.

Stephen breaks this down into a video https://vimeo.com/631148329/5cb023d6df
And laso in the figma mockups https://www.figma.com/file/oEvgHnycgPINuXuQV57rD7/Phoenix-Notes?node-id=34%3A879

![Screenshot 2021-10-14 at 00 33 13](https://user-images.githubusercontent.com/36959754/137221697-c8041f03-7019-43bd-8a69-5d56d7460cad.png)
![Screenshot 2021-10-14 at 00 33 20](https://user-images.githubusercontent.com/36959754/137221699-87c6b51d-15d9-4ed0-924f-ebd18b4410af.png)
![Screenshot 2021-10-14 at 00 33 26](https://user-images.githubusercontent.com/36959754/137221701-0e7a89fd-4128-4fb0-906f-d104ca78cdf1.png)

The flow proposed also tackles the problem of that first payment where user would create an invoice last than 10 000.

If you guys are willing to explore this we can break it into a issue on it's own.

**Comment by robbiehanson** [comment]
Moved into separate issue #263
