### ISSUE TITLE
Add 'Hide sensitive values' feature

### ISSUE THREAD

**Issue by Bosch-0** [ACINQ/phoenix#208]
Having the option to hide sensitive values (balance, transaction amounts etc.) is something quite common in Bitcoin wallets and is a good security / privacy practice to enact in general. There is several ways to do this though I believe the least intrusive is tapping and holding the balance to hide / reveal sensitive information. Design mockup below: 

![image](https://user-images.githubusercontent.com/55287964/137436994-c2ff6b06-73f7-4a9c-bc43-07efabb7e47a.png)

**Comment by robbiehanson** [comment]
Thank you once again for all the help & suggestions.

**Comment by Bosch-0** [comment]
No worries! I love Phoenix, I'd be interested in helping out whenever possible. Just tag me on here or dm me over on the bitcoin desgin Slack - [bitcoin.design ](https://bitcoin.design/)
