### ISSUE TITLE
Payment stuck for hours

### ISSUE THREAD

**Issue by haukehess** [ACINQ/phoenix#22]
I started sending 25k sats. Then I tried to send 650k (yes, that was mean of me!), and this payment is stuck. Since 3 hours.
Sending from "Wallet of Satoshi" to Phoenix.

I knew that this would be a challenge because the initial channel wouldn't be large enough to hande this. I assume this might be a standard ux where the user needs to build trust with Phoenix before sending larger amounts.

When will my payment timeout?
Is this channel capacity issue by design or a bug?

**Comment by pm47** [comment]
Hi, can you share your logs by email (phoenix@acinq.co)?
