### ISSUE TITLE
Advanced security info page doesn't return to previous page after closing

### ISSUE THREAD

**Issue by EZ0010** [ACINQ/phoenix#223]
Hi, I found small bug:
Settings -> App access -> Advanced security -> click the "?" button
the close button doesn't do anything, I clicked more than once, and when you swap the page down it takes you to the main settings page not the previous "App access" page.

here is a demo

https://user-images.githubusercontent.com/75021359/143072041-2a079699-845b-4a25-bbfc-487a8fe8ff3c.mov

**Comment by robbiehanson** [comment]
This appears to be an iOS 15 bug (concerning the use of `NavigationLink`'s). I have a fix for the issue. Currently testing backwards compatibility with iOS 14...

**Comment by robbiehanson** [comment]
Thanks for reporting this bug. It should be fixed in the next release: v1.2.1

**Comment by robbiehanson** [comment]
For my future reference: https://developer.apple.com/forums/thread/677333
