### ISSUE TITLE
UI suggestion for description saving button

### ISSUE THREAD

**Issue by EZ0010** [ACINQ/phoenix#224]
I think it would be better to swap cancel with the "save" button

Cancel placement make sense for saving in my opinion, I mistakenly clicked cancel without reading thinking it is the save button.

![image](https://user-images.githubusercontent.com/75021359/143086206-ade78665-c5d7-45ba-a2c2-b150c47d2be7.png)

something like this maybe is better?

![Untitled-1](https://user-images.githubusercontent.com/75021359/143086826-0a5534fb-d079-4230-879f-4816e316ea03.png)

**Comment by robbiehanson** [comment]
> I mistakenly clicked cancel without reading thinking it is the save button

I did the exact same thing yesterday :rage: This definitely needs to be fixed.

**Comment by robbiehanson** [comment]
When I was playing around with it, I hit the back button automatically (when I wanted to save). I guess the explicit save/cancel is just kinda foreign to iOS. So I came up with a different design:

<img height="400" alt="Screen Shot 2021-11-24 at 10 01 27" src="https://user-images.githubusercontent.com/304604/143262672-9174796d-a30c-42e4-8cbd-4b04d28203a8.png">

**Comment by EZ0010** [comment]
Looks amazing :) thanks for listing to users feedback.
