### ISSUE TITLE
Path finding issues for payments.

### ISSUE THREAD

**Issue by niteshbalusu11** [ACINQ/phoenix#228]
All the payments below are going to the same node, routes are failing due to path finding issues constantly. Maybe bad channels should be avoided more in path finding. 

![image](https://user-images.githubusercontent.com/84944042/146304223-490cce7a-c576-4dc6-a3cb-020ca6118624.jpeg)

![image](https://user-images.githubusercontent.com/84944042/146304238-8eac48f1-1ecd-43bb-bbe2-265cc853e60f.jpeg)

![image](https://user-images.githubusercontent.com/84944042/146304250-6fe7bfda-9b36-4352-8343-8e3028f24d75.jpeg)

![image](https://user-images.githubusercontent.com/84944042/146304258-6b7eb3d5-4004-48a6-8a44-c1f3edea03f7.jpeg)

**Comment by dpad85** [comment]
> All the payments below are going to the same node, routes are failing due to path finding issues constantly

What node is that? Is it a stable and well connected node? FYI in the 2nd screen `Incorrect payment details...` is not a routing error but a payment failed by the receiving node, usually because it does not know the payment hash you're trying to pay.

**Comment by niteshbalusu11** [comment]
> > All the payments below are going to the same node, routes are failing due to path finding issues constantly
> 
> 
> 
> What node is that? Is it a stable and well connected node? FYI in the 2nd screen `Incorrect payment details...` is not a routing error but a payment failed by the receiving node, usually because it does not know the payment hash you're trying to pay.

Is it my own routing node. It is very stable and pretty well connected. And yeah, the 2nd screenshot is my bad, put in the wrong one. But there are more that failed due to path finding.
