### ISSUE TITLE
Why won't Phoenix connect to my public Electrum server?

### ISSUE THREAD

**Issue by sumBTC** [ACINQ/phoenix#23]
First of all: awesome project!

I run a public Electrum server at: `217.104.4.71:50512` called `Bitkoins.nl`.

When I specify that IP address and port in Phoenix (as: 217.104.4.71:50512)  it won't connect (keeps saying "Connecting to electrum server") while if I specify my server in exactly the same way in the Electrum wallet App on android, it connects without problems (displaying the correct number of blocks)

**Comment by dpad85** [comment]
Hello,

Are you using a self-signed certificate on your electrum server? Phoenix checks that the certificate is valid when you want to connect to a specific electrum server. If the certificate for this server is self signed, the connection will not go through and fail, this is intended.

**Comment by sumBTC** [comment]
Hi, yes it's self-signed. I did found out recently how to generate certificates with letsencrypt. My website Bitkoins.nl is now a correct https-site as you can verify. Should I use these certificates for my Electrum server or what should I do?

**Comment by dpad85** [comment]
With a self signed certificate, Phoenix cannot actually verify that you are really connecting to your own server, giving you a false sense of privacy/security.

We could take a more sophisticated approach, accept the self-signed certificate on first connection, then check for changes in the fingerprint and warn the user; but people typically ignore warnings and just click "OK", so it's not very helpful.

If you don't want to use a CA, a good solution would be to use TOR, and we are working on making this easy to do with Phoenix. 

> Should I use these certificates for my Electrum server or what should I do?

Yes you can use your let's encrypt certificate.

> Why is it good enough for the Electrum App?

I don't know how they do it.

**Comment by sumBTC** [comment]
Thanks for all the answers, really appreciated. I'm also running an electrum server over tor, so that would be a solution for me personally. Because I run a public electrum server, I want as many people as possible to make use of it so when I have time I'll look into getting my let's encrypt certificate to work with electrumx. I'll close the issue. Thanks again!

**Comment by sumBTC** [comment]
@dpad85 I managed to get it working! My electrum server is now at electrum.bitkoins.nl, port 50512 and it's accepted by Phoenix. Nice to know it can now be automatically selected from the server list (and maybe by other services/apps). Thanks for all the help.
