### ISSUE TITLE
Invoice expiration settings/configuration (Bolt #11)

### ISSUE THREAD

**Issue by braydonf** [ACINQ/phoenix#235]
When attempting a pull-payment with Phoenix from [BTCPayServer](https://github.com/btcpayserver/btcpayserver), as in the case of a refund, it will warn "The BOLT11 invoice must have an expiry date of at least 30 days from submission (Provided was only 6)".

Is there a way to configure the expiration date? If not I think this would make a good feature.

**Comment by braydonf** [comment]
Please see associated issue https://github.com/btcpayserver/btcpayserver/issues/3281

**Comment by dpad85** [comment]
For now this expiry is 1 week and is not configurable (ios or android). That could be useful indeed, we could add that setting next to the default invoice description.

**Comment by robbiehanson** [comment]
Configuration option added to iOS via PR #239
