### ISSUE TITLE
(iOS) RTL issues

### ISSUE THREAD

**Issue by EZ0010** [ACINQ/phoenix#237]
Here are some issues and improvements to the app when the language is RTL (such as Arabic):

![image](https://user-images.githubusercontent.com/75021359/149653148-81477558-b162-4584-8935-a8fe1ebb287d.png)

**Comment by EZ0010** [comment]
Fees explanation popup is misaligned
![Simulator Screen Shot - iPhone 13 Pro - 2022-01-16 at 12 14 23 (1)](https://user-images.githubusercontent.com/75021359/149655773-ff4bffbe-1835-411c-aa1e-abcc3c40b301.png)

**Comment by EZ0010** [comment]
Hi again, thanks for the fixed, I checked it and everything looks great!

I found another small issues:

1. the gray amount in sats is misaligned
<img width="528" alt="Screen Shot 2022-01-27 at 12 15 23 PM" src="https://user-images.githubusercontent.com/75021359/151328566-0b02d0ff-5755-4814-b641-a96d0dcdf6da.png">

2. channel information should be LTR
<img width="528" alt="Screen Shot 2022-01-27 at 12 17 56 PM" src="https://user-images.githubusercontent.com/75021359/151329011-ae136549-9a0c-4855-aef5-6982e93d5373.png">

3. if possible add more room for this text, there are 3 words missing.
<img width="528" alt="Screen Shot 2022-01-27 at 12 25 31 PM" src="https://user-images.githubusercontent.com/75021359/151330745-f329d7e2-649a-4a0f-a45c-5768080957fd.png">

**Comment by robbiehanson** [comment]
> the gray amount in sats is misaligned

Can you give me more clarity on this. It currently reads "sat .015153-". I'm guessing this is wrong. What should it be?

**Comment by EZ0010** [comment]
> Can you give me more clarity on this. It currently reads "sat .015153-". I'm guessing this is wrong. What should it be?

it should be "sat -153.015"
numbers in RTL are just like LTR languages, you read them from left to right (look at the fees on the same screen, it is rendered without issues), maybe the only difference is the "sat" is on the other side of the number so if "sat" is translated it should be like this
![image](https://user-images.githubusercontent.com/75021359/151364528-e3c7129e-2fa8-4697-87ed-118a5910de7a.png)

**Comment by EZ0010** [comment]
Thanks for the fixes and support for RTL languages.
I will close the issue
