### ISSUE TITLE
[UX] (Legacy) Back button from "Use LNURL link" take you home

### ISSUE THREAD

**Issue by EZ0010** [ACINQ/phoenix#238]
on Android Legacy app

Receive -> Use LNURL link -> click back arrow
The user expect the back arrow to take you back to receive screen, but it takes you to home screen.

**Comment by dpad85** [comment]
That's a good point. It has been done so to keep things a bit more simple in the app. That won't be fixed because the legacy app is already being completely rewritten with a new framework that make that kind of navigation logic easier to write.
