### ISSUE TITLE
amount field shows "invalid amount" in fiat currency when layout is RTL

### ISSUE THREAD

**Issue by EZ0010** [ACINQ/phoenix#249]
Hi again, sorry for constantly opening issues, I've been testing the wallet with every kind of scenario :) hope this might be last issue.

1. From iOS settings change Phoenix default language to Arabic.
2. Click receive -> modify amount -> type in an amount -> choose USD
it will give you an error "Enter a valid amount", this issue is only when choosing a fiat currency, sats and btc works fine.
![image](https://user-images.githubusercontent.com/75021359/153759595-fc55c522-c92a-4c9a-b351-66e5e024543b.png)

Also, I noticed on some screens (such as iPhone 13 pro) some amounts aren't shown fully, not sure if that is an issue or because the screen is smaller than others (iPhone 13 max doesn't show the error)

1. try to pay an invoice for "1337 sats"
2. it will cut a part of the amount and it will show it if you click to edit it
3. also it will show the error "Enter a valid amount" if you choose USD (note: in this screenshot I choose sats but the error shown is because I don't have a balance, not an invalid amount)

![image](https://user-images.githubusercontent.com/75021359/153759916-cbe1c874-34af-4a03-98b9-4cfcde0e5999.png)

**Comment by robbiehanson** [comment]
> hope this might be last issue

We hope not :smile: We want the app to be **solid**. In every language. In every part of the world. And for that, we need lots of testing & feedback. We appreciate the issues you open.

**Comment by robbiehanson** [comment]
Thanks again for reporting this.

> it will give you an error "Enter a valid amount"

I discovered that the bug was also affecting other regions, such as the Netherlands !

> it will cut a part of the amount and it will show it if you click to edit it

This appears to be a SwiftUI bug. In iOS 14, these text-truncation bugs were more common. It looks like Apple fixed many of them in iOS 15, but I wouldn't be surprised if they still occur occasionally in RTL. Let us know if you see any others.
