### ISSUE TITLE
Multipath payment to lnd v0.9.0-beta failed

### ISSUE THREAD

**Issue by ppppso** [ACINQ/phoenix#25]
[lnd v0.9.0](https://github.com/lightningnetwork/lnd/releases/tag/v0.9.0-beta) supports receiving multipath payments, however I tried sending a multipath payment from Phoenix to lnd v0.9.0 and it failed. I tried both with and without amount and in both cases it failed. Error is `incorrect payment details or unknown payment hash`.

**Comment by t-bast** [comment]
We will need more details than that to be able to troubleshoot.
Can you provide the invoice you're trying to pay for example?

**Comment by ppppso** [comment]
Sure (might be expired by now though).

`lnbc2500u1p0ygrpkpp5z749z0v7muyt3xd8matv5klxxy9xw0mpv4qtvf8wn5ke023jacmsdpq2dhh2argtp3ksctwvajjq3r9wphhx6t5cqzpgxqzyksp5xsj3zgy8dnzxe3d0py9xt5d0y8dr8sfrj5vuz4vg4wkng6y7tu4q9qy9qsq4tx082r4x8agt9ru3avg69qpe4xr3jqry8m4x75p7lwgj68vscm84vwq22hca3p5xsvtz9l3cckwuydle70cvdceptypsswgmszqp4gqujg7te`

**Comment by t-bast** [comment]
Our node couldn't find a route to your node.
Do note that for now, only Phoenix to Phoenix scenario use MPP all the way to the recipient.
When sending to a non-Phoenix recipient, the Acinq node will try to forward the payment as a single part.
So if there is no route that allows routing the whole amount, it will fail (which is what is happening here).

We will enable MPP all the way to any recipient in the future, but the splitting algorithm needs more fine-tuning before we can confidently enable it on our node.
