### ISSUE TITLE
Validate and decode LNURL using phoenix: scheme prefix on Android

### ISSUE THREAD

**Issue by tim-edwards** [ACINQ/phoenix#251]
I can send an LNURL withdrawal request using a deep link directly to Phoenix using something like the following "lightning:LNURL123...123". However anyone with more than one lightning wallet finds it impossible to have the URI open the correct wallet since the OS (especially iOS) just opens the last wallet installed which supports the "lightning:" url scheme.

On iOS I can open Phoenix directly, and have the wallet process the invoice successfully using the following url scheme "phoenix:lightning:LNURL123...123". I can see in the code this was a requested feature:

As well as adding both "lightning" and "phoenix" into the Info.plist CFBundleURLTypes; in SceneDelegate.swift you have:

```
func handleExternalURL(_ url: URL) {
	log.trace("handleExternalURL")
		
	var urlStr = url.absoluteString
		
	// We support phoenix-specific URLs:
	// phoenix:lightning:lnbc10u1pwjqwkkp...
	//
	// As per issue #186:
	// > Anyone with more than one lightning wallet on iOS has a hard time
	// > having the URI open the correct wallet...
	//
	let trimMatchingPrefix = {(prefix: String) -> Void in
			
		if urlStr.lowercased().starts(with: prefix.lowercased()) {
				
			let startIdx = urlStr.index(urlStr.startIndex, offsetBy: prefix.count)
			let substr = urlStr[startIdx ..< urlStr.endIndex]
			urlStr = String(substr)
		}
	}
		
	trimMatchingPrefix("phoenix://")
	trimMatchingPrefix("phoenix:")
		
	AppDelegate.get().externalLightningUrlPublisher.send(urlStr)
}
```

However on Android I'm afraid this method doesn't work.

I can see in AndroidManifest.xml within phoenix-legacy you have set the Intent filter for "lightning", however it does not contain "phoenix". Can I assume this code might be old now since I can see a new Kotlin project in the phoenix repo?

```
<!-- handle payment uris -->
<intent-filter android:label="@string/app_name">
  <action android:name="android.intent.action.VIEW" />

  <category android:name="android.intent.category.BROWSABLE" />
  <category android:name="android.intent.category.DEFAULT" />

  <data android:scheme="bitcoin" />
  <data android:scheme="lightning" />
  <data android:scheme="lnurl" />
</intent-filter>
```

Would it be possible to allow either the "phoenix:" or "phoenix:lightning:" scheme to decode and process the invoice in the Android version? This would allow us at THNDR Games to add support for Phoenix wallet for our sats prize payments on Android.

Thanks!

**Comment by robbiehanson** [comment]
Related to issue #186

@dpad - As noted above, on the iOS side I:
1. Added support for "phoenix:" URLs to Info.plist
2. Added code to trim the "phoenix:" prefix **before** sending it to Kotlin layer

Step 2 can be moved into the Kotlin layer when you're ready.

**Comment by dpad85** [comment]
This has been fixed in the legacy app and will be available in the next release of Phoenix android.

**Comment by dpad85** [comment]
Available with v1.4.26 (android)

**Comment by tim-edwards** [comment]
Thank you for fixing this @dpad85  🙏 

I have re-enabled Phoenix wallet (Android) in all our games at THNDR today 🔥

**Comment by dpad85** [comment]
Great 🥳 ! Thanks for the update.
