### ISSUE TITLE
App crashes after LNURL withdraw 

### ISSUE THREAD

**Issue by taxmeifyoucan** [ACINQ/phoenix#26]
- App is newly installed
- Open an app with a fresh wallet
- Scan LNURL on the Receive tab 
- Once you hit Withdraw app crashes

However sats are received and after reopening the app funds are there and everything seems ok. This happens every time when you use LNURL, not only after fresh install. I am attaching the log, might help I guess. 

[phoenix.log](https://github.com/ACINQ/phoenix/files/4226650/phoenix.log)

**Comment by dpad85** [comment]
Hello,

There was a similar bug that has been fixed in v1.1.1.

What version of Phoenix are you using? You can see the current installed
version in your Android system settings > applications > Phoenix

**Comment by taxmeifyoucan** [comment]
It says 1.1.1, newest update from Play Store.

**Comment by dpad85** [comment]
My bad, the fix was not included in 1.1.1, but in the next version which will be released very soon.

**Comment by taxmeifyoucan** [comment]
Perfect, thanks! Looking forward to the new version.
