### ISSUE TITLE
[Android] Exchange rate seems stuck and not updating for DKK

### ISSUE THREAD

**Issue by jannickj** [ACINQ/phoenix#267]
I show my currency as DKK but it seems like the amount has stuck?, it is currently showing 310 satoshi / dkk and it has been for some time now but the real number on all the exchanges are 360 satoshi / dkk.

**Comment by robbiehanson** [comment]
We were previously using a CoinDesk API to fetch exchange rates for many currencies, including DKK. But their API stopped functioning properly, and we received multiple reports about incorrect exchange rates for about a dozen different currencies.

We fixed the issue via https://github.com/ACINQ/phoenix/pull/331

For iOS, the fix will be released via v1.5.5
For Android, the fix will be released in the next major version release

Sorry for the delay on Android. We're in the middle of a **major** update on the Android side, so it make take a bit longer.
