### ISSUE TITLE
Phoenix wallet incorrectly shows a transaction as received successfully

### ISSUE THREAD

**Issue by Webjin** [ACINQ/phoenix#277]
First time trying out phoenix (and a LN wallet for that matter)
But I'm running into some strange behavior.

I've done a withdrawal from Nicehash, over the LN network to the wallet on my phone.
On Nicehash the withdrawal shows as failed (because I tried to withdraw within 24 hours after activating 2FA)
![image](https://user-images.githubusercontent.com/1696487/169036285-16c192d8-cb2d-44b9-8e00-6c2e6523c071.png)

But on my phone it shows the transaction itself as successful (see the checkmark icon) . Even deducted the fee for opening a new channel.  But obliviously didn't add to my balance.
See screens. (differences in Euro value is due there's a few days difference in when I took the screenshots.

<img src="https://user-images.githubusercontent.com/1696487/169037367-0251bc81-813d-452d-98a2-748f1e8c4085.png" width="300">
<img src="https://user-images.githubusercontent.com/1696487/169037403-ab785a12-b602-4a19-8aa7-b34519d5df07.png" width="300">

I think one of the proper fixes would be to show that the transaction has failed

--------------
Update.
Second transaction from Nicehash, which is successful, has the channel fee substracted (correctly).
So really, my only feedback is that there should be a visual indicator that a transaction has not actually come through
<img src="https://user-images.githubusercontent.com/1696487/169041421-13156312-3cef-40ea-af94-388b76bae5cb.png" width="300">

**Comment by robbiehanson** [comment]
Sorry this slipped thru the cracks. Please contact support if you have issues: https://phoenix.acinq.co/support

GitHub is only used for engineering related stuff.
