### ISSUE TITLE
Allow setting the expiry of an invoice (to a large value)

### ISSUE THREAD

**Issue by ghost** [ACINQ/phoenix#28]
When generating an invoice to receive a payment, it makes sense to set the expiry to a large value (many days even). For example, in my lightning [game](https://BitcoinDayTrader.nl) I need to pay people if they win. However, the payment may fail because of a server problem or because there isn't a route. In the first case I need time to retry at a latter date and in second case I need to open a new channel which may take some time if I don't want to pay a high on-chain fee. 

I realize this is a specific example but I can imagine that the need to open an extra channel may occur more frequently.

So that feature would be nice. I don't know, however, if longer expiry times are a burden for a lightning node.

**Comment by t-bast** [comment]
I think it's a reasonable feature request, we'll have a look at it.

**Comment by robbiehanson** [comment]
Closing as requested. Note that a similar issue has resurfaced in #235
