### ISSUE TITLE
LNURLw no longer scannable

### ISSUE THREAD

**Issue by Liongrass** [ACINQ/phoenix#295]
I noticed with the recent Phoenix iOS update (1.5.0) that LNURL-withdraw are no longer scannable. I believe this is a bug as I did not see any announcement that LNURL-w would no longer be supported.

Repro:
- Open Phoenix in iOS (version 1.5.0 on iOS 15.6.1)
- Scan a LNURLw

Expected:
- Phoenix would open the usual LNURL-withdraw dialogue

Actual:
- Error message:  "This doesn't appear to be a Lightning invoice"

Thank you for your help with this!

**Comment by dpad85** [comment]
This would be a bug indeed, we have no intentions of stopping support for lnurl-withdraw. What withdrawal service/wallet have you tested Phoenix with?

**Comment by Liongrass** [comment]
Hi! Thank you for your reply. I've tried this with with LNURLs created with LNbits, both from the legends.lnbits.com server and my own. When pasting a LNURLw from the clipboard the LNURLw seems to be recognized by Phoenix, but the dialogue seems to be stuck at "fetching invoice."

Scanning/pasting LNURLp created with the same servers resolve without an issue.

**Comment by robbiehanson** [comment]
Thanks for reporting this. We did indeed accidentally break LNURLw. The patch has been committed, and it should be fixed in the next version release. We'll try to get that out soon.

**Comment by Liongrass** [comment]
I just scanned a LNURLw QR code with Phoenix, and got the error "This doesn't appear to be a Lightning invoice" again. I was able to redeem it copying the raw LNURLw by selecting "Paste from clipboard" though. Not sure I tested scanning QR codes last month when this ticket was closed or if this is a reintroduced bug.
