### ISSUE TITLE
Support for ARS currency is not working in Android

### ISSUE THREAD

**Issue by diegogurpegui** [ACINQ/phoenix#296]
Support for Argentinian Peso currency (ARS) was added in this PR: https://github.com/ACINQ/phoenix/pull/254
However, it's not present in the Android app and from a quick look in the PR it should be. I will keep looking and see if I can add the change myself, but I wanted to leave this here in case there is an actual bug or a reason for this.

**Comment by robbiehanson** [comment]
When we added support for iOS a few years ago, we rewrote the core library in Kotlin Multiplatform, and then added a native iOS UI on top of it. So the code you're referring to is within the Kotlin library, and therefore (currently) only available on iOS. However, we're currently in the process of migrating the Android app to use the new Kotlin library. (That was the motivation to use Kotlin MPP - so we could maintain a single library for both iOS & Android.) So these currencies (ARS official & blue market) will be available on Android soon.
