### ISSUE TITLE
Please Assist with lightning-kmp:1.4.2-SNAPSHOT error

### ISSUE THREAD

**Issue by adukugideon** [ACINQ/phoenix#300]
Hello, I tried to build off the latest branch but it looks to me as if the lightning-kmp version used is not available as gradle cannot even find it anywhere. 
Below is the error I encountered:
`Could not find fr.acinq.lightning:lightning-kmp:1.4.2-SNAPSHOT.
Required by:
    project :phoenix-shared`

Looks to me as if its not available on the Nexus repository as well. I checked here: [https://oss.sonatype.org/#nexus-search;quick~lightning-kmp](url)
Any advice and solution would be much appreciated.

**Comment by sstone** [comment]
Hello, see https://github.com/ACINQ/phoenix/blob/master/BUILD.md#build-lightning-kmp
