### ISSUE TITLE
Coindesk API provides inaccurate fiat conversions rates

### ISSUE THREAD

**Issue by zikziko** [ACINQ/phoenix#304]
While using wallet i came across strange currency conversion. The coindesk api reports vastly different prices from other providers or even from their own web version.
https://api.coindesk.com/v1/bpi/currentprice/CZK.json
https://www.coindesk.com/price/bitcoin/ 
the problem seems to affect all non USD currencies.

The behavior can be huge missmatch for EUR
https://api.coindesk.com/v1/bpi/currentprice/EUR.json
given the recent EUR drop in price against USD. As of writing(19 169 USD) API price:  18 673 EUR   vs "real price":  19 720 EUR.

**Comment by dpad85** [comment]
Are you using Phoenix on Android or on iOS?

FYI, on both the Android app and the iOS app, the EUR/BTC and USD/BTC tickers come from the blockchain.info API, so we do not use Coindesk there, and the rates are accurate (right now the rate in the app is 1 btc = 19 974 EUR, which is correct).

Coindesk is used for the currencies other than USD/EUR, and that's where there can be discrepancies. We're aware of that and we have plans to fix that in the future.

**Comment by zikziko** [comment]
I've seen the EUR only in the API and didn't check phoenix itself, sorry for this misinformation. I'm using the app on Android. I'm glad you are aware of the issue for other currencies. It seems to me that coindesk is using some old exchange rates between USD and other currencies which is causing this behavior.

**Comment by robbiehanson** [comment]
Notes:
- We've had reports of inaccurate SEK, Swedish crowns (ticket 47508568)
- We don't currently support [CNH](https://wise.com/us/blog/cny-vs-cnh), but we would like to

**Comment by robbiehanson** [comment]
Exchange rate for COP is very inaccurate recently. For example, today:
- coindesk: 1 USD = 4,219 COP
- everybody else: 1 USD = 4,757 COP

**Comment by robbiehanson** [comment]
The raw JSON from the coindesk feed contains this disclaimer:

> "This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org"

However, if I pull directly from the source, I get very different exchange rates:

- direct from CoinDesk API: 1 USD = 4,218.99 COP
- direct from OpenExchangerRtes API: 1 USD = 4,765.08 COP

So the OpenExchangeRates API has an accurate value, while CoinDesk does not. So if CoinDesk is indeed pulling from this source, then they're doing so poorly (either infrequently, of their update job is crashing).

**Comment by robbiehanson** [comment]
Fixed via PR #331 
It will be available in the next (major) app release: v1.6.0
