### ISSUE TITLE
Feature Request: Add an option to use "Legacy LN-Auth" 

### ISSUE THREAD

**Issue by MTG2000** [ACINQ/phoenix#328]
Hello there.

I've been using phoenix wallet to login to some websites using LN-Auth, but recently, it seems that the key generation method changed inside the wallet?

Because when I'm trying to login to my accounts on some websites, it's creating new accounts for me instead of logging me in to my existing accounts...
So currently I'm unable to enter any of my original accounts anymore... ☹️ 

Wondering if it's possible to add an option setting in the wallet to make it use the old ln-auth protocol similar to how Alby added a "Legacy LN-Auth" option??

Or if there is another way to recover my old accounts, please let me know.

Thanks a lot.

**Comment by dpad85** [comment]
Hey, are you on Android or iOS? The Android app already lets you use a legacy compatibility mode, in settings > payment options.

Can you also share what service you are trying to log into?

**Comment by MTG2000** [comment]
I'm on Android.

I can't find this option:
![image](https://user-images.githubusercontent.com/50504183/209795771-1da01863-c665-41ab-bac7-980f596b776d.png)

The service I'm trying to login to is:
https://makers.bolt.fun

**Comment by dpad85** [comment]
We did not take https://makers.bolt.fun/ into account for the backward compatibility fix added in version 1.4.24. I'll fix that in the next release, sorry for the inconvenience.

**Comment by MTG2000** [comment]
Hey @dpad85 
I see that a fix has been pushed yesterday.

Is the problem supposed to be fixed in the wallet now??

(Because today, a user reported again that he wasn't able to login to his original account using Phoenix)

**Comment by dpad85** [comment]
The version containing the fix has not been published yet, I'll let you know when it's ready. Should be soon.

**Comment by dpad85** [comment]
The fix has been published, you'll need version 1.4.25 on android or 1.5.5 on iOS. Please reopen this ticket if you still have issues.

**Comment by MTG2000** [comment]
Great!
Thanks a lot @dpad85 🙏

**Comment by swedishfrenchpress** [comment]
Hey @dpad85. I just updated my iOS verison to 1.5.6 and I am still having a problem logging into bolt.fun. When I login I am being assigned a new profile. In the past I used Phoenix to setup and manage my old profile. The recent update didn't appear to solve my issue. Is there anything I can do to help troubleshoot?
