### ISSUE TITLE
Cannot receive bitcoin with LNURL

### ISSUE THREAD

**Issue by akkien** [ACINQ/phoenix#330]
I scanned LNURL from https://lightningnetworkstores.com/faucet to receive payment. After clicking Redeem for a while, the website showed success but the app screen did not change. And I do not receive any bitcoin in the wallet.

When I use another wallet like Wallet of Satoshi, it works properly.

**Comment by dpad85** [comment]
This is probably an issue with the faucet and not Phoenix. In any case we can investigate but this is not the right place for that. Please send an email to phoenix@acinq.co with the payment hash (or the invoice), we'll take a look and see if that payment actually went through.
