### ISSUE TITLE
Wallet offline

### ISSUE THREAD

**Issue by robbiehanson** [ACINQ/phoenix#350]
We've had several reports of wallets stuck in Offline mode:

<img height="450" src="https://user-images.githubusercontent.com/304604/228581469-cbad6c34-0bba-4e96-ac8c-75f517e9c88a.png"/>

We've gathered the following information from the reports:

- known to affect both iOS 15 & 16
- SwiftUI seems unaffected, but the underlying Kotlin layer seems to be frozen or otherwise non-responsive

**Comment by robbiehanson** [comment]
Theory 1: Maybe the wallet isn't unlocked because:

- the read-from-keychain request never returned or
- the `loadWallet` function returns early (thinks wallet is already loaded)

Tests performed:

if the read-from-keychain request never returns, the UI is stuck in this state:

<img height="450" alt="if keychain request is dropped" src="https://user-images.githubusercontent.com/304604/228584022-5b248ea6-8fe2-41b1-92b2-b540538a63c8.png">

if the `loadWallet` function returns early, then the app crashes because of various assumptions, such as this one within the `AppStatusButton`:

```
let syncTxManager = Biz.syncManager!.syncTxManager
```

**Comment by dpad85** [comment]
Another theory: an issue when serialising and/or uploading a payment to iCloud would deadlock the node bootstrap, leading to a responsive UI but a frozen node.

**Comment by tschweg** [comment]
> Another theory: an issue when serialising and/or uploading a payment to iCloud would deadlock the node bootstrap, leading to a responsive UI but a frozen node.

Maybe this helps:
I've had connectivity issues with the lightning node today after a prolonged period of not using the app (about a month or so). 

Setup:
- Tor: Disabled
- iCloud Backup: Enabled
- Randomized upload: Disabled

Ive tried the following to get it to connect:
- Switch from wifi to cellular: no luck
- Enable/Disable Tor: no luck
- Disable iCloud Backup: Successful connect

After successful connect, I've re-enabled iCloud backup again, quit the app and relaunched. It now connects to LN properly again. 🤷
