### ISSUE TITLE
UX Research / Interview

### ISSUE THREAD

**Issue by swedishfrenchpress** [ACINQ/phoenix#359]
Hey guys, My name is Erik (https://twitter.com/uxerik_) and I'm a UX designer focused on Bitcoin. I've been using Phoenix wallet and I'm very impressed by how your team has managed to design onboarding process that is both very UX friendly and self-sovereign. The setup process is quite remarkable considering Phoenix wallet manages to open up payment channels and assign a user a node ID. From a UX point of view I'm interested in learning more. I want to conduct some explorative user research on the Phoenix onboarding process in order to share with the open source Bitcoin Design Community (https://bitcoin.design/).

Is it possible to set up a 30 minute call with a developer, product manager, or designer on the Phoenix team? I want to ask a few questions about your approach to onboarding, what exactly is happening under the hood, and the design / UX trade offs of Phoenix. 

Cheers,
Erik

**Comment by dpad85** [comment]
Hello Erik,

Thanks for the kind words! The current onboarding process is explained in this blog post: https://medium.com/@ACINQ/phoenix-part-2-pay-to-open-4a8a482dd4d, the post is quite old but still technically correct.

However with [splicing](https://github.com/lightning/bolts/pull/863) and [dual funding](https://github.com/lightning/bolts/pull/851), the onboarding process on Phoenix will be changed and improved. Once this update is ready, we'll write a in-depth blog post which will explain how and why those changes were made, especially the impact on the UX.
