### ISSUE TITLE
Question - When will be phoenix-android ready for translating?

### ISSUE THREAD

**Issue by MasterixCZ** [ACINQ/phoenix#361]
TRANSLATION.md states that no effort should be made to translate. So when will it be ready?
 I am willing to help translate Phoenix into Czech.

**Comment by dpad85** [comment]
Hey, I think it should be ready in the coming weeks. Basically, you can keep an eye on PR https://github.com/ACINQ/phoenix/pull/356 and once it's merged you should be able to start working on the translation 👍

**Comment by dpad85** [comment]
Closing this issue, the new app is now ready for translation (and was localised into Czech).
