### ISSUE TITLE
Binance does not accept Phoenix invoice format

### ISSUE THREAD

**Issue by jbrepogmailcom** [ACINQ/phoenix#382]
Binance just launched ability to deposit and withdraw BTC over LN. I tested deposit from Phoenix -> Binance. It works well, payment there in 20 sec. But the other way is the problem. I generate invoice in Phoenix, copy it to clipboard and paste to Binance LN Withdraw field. I get error that "Invoice is not reachable". So sending from Binance to Phoenix over LN does not work.

**Comment by bitcoinuser** [comment]
Same problem for me using Phoenix.

**Comment by ekzyis** [comment]
Binance probably does not support routing hints yet. So I don't think this is a problem on ACINQ's side. You should tell Binance about this. ACINQ can't fix this since their wallets are private nodes. The sender must support routing hints to send to private nodes afaik.

**Comment by bitcoinuser** [comment]
Binance fixed it
