### ISSUE TITLE
Displaying ?! instead of amount of money in CZK

### ISSUE THREAD

**Issue by danielkonecny** [ACINQ/phoenix#384]
Hey,

I changed the currency in the app settings to Czech koruna (CZK) but I don't see any amounts of money in the app homepage, only "?!" in the correct spots. This is for the total amount as well as for all the transactions in the transaction list and in the transaction detail. The amount in sats is displayed correctly.

App version: splices-beta4
Android version: OxygenOS 13.0 (based on Android 13)
Device: OnePlus Nord2 5G

Let me know if there are any additional details I should provide.

Thanks in advance for fixing this!

**Comment by danielkonecny** [comment]
The value in currency changed to CZK is now displayed correctly. It took approximately a day but it was fine then. I'm not sure whether some cached value had to get updated or some currency exchange rates loaded, might be one of those.

Nevertheless, I would still consider this a bug, since it took some time to get corrected without notifying the user about this. Running a beta version, I expect to run into issues like this and am fine with them, but it might not be the same for other users if it gets into production release.

**Comment by dpad85** [comment]
Thanks for creating the issue for this bug. It's a bug in the migration process, and it will be fixed before production.
