### ISSUE TITLE
Zero balance, after uncommanded channel closing.

### ISSUE THREAD

**Issue by aprilinph** [ACINQ/phoenix#387]
Channel closed for no reason i see, and confirmed onchain many txs ago.
Phoenix still showing 0 sats.

How to recover and send out to other wallet?

**Comment by dpad85** [comment]
To recover funds from force-closed channels, see this entry in the FAQ: https://phoenix.acinq.co/faq#my-channels-got-force-closed-how-do-i-recover-my-money

Closing this ticket, support is done by email : phoenix@acinq.co.
