### ISSUE TITLE
Millisat part should be truncated when converting an amount input from fiat to btc

### ISSUE THREAD

**Issue by dpad85** [ACINQ/phoenix#388]
When making a LN payment to a Lightning address, if the user inputs an amount in fiat, the btc amount expected by Phoenix will most certainly contain a millisat decimal part, due to the conversion. 

However some services/wallets like WalletOfSatoshi do not handle millisats and will generate an invoice whose amount is rounded up. As such Phoenix correctly rejects the invoice, because the actual amount does not match the expected amount.

Even if that's a bug in those services, Phoenix should be smarter. The solution is to not use millisats when converting an input from fiat (though the user should still be able to enter a millisat amount if the input is in btc).

**Comment by dpad85** [comment]
To reproduce this issue on Android or iOS : make a payment to wallet of satoshi using Lightning address, and use an amount of $1. Phoenix will reject the invoice due an incorrect amount.

**Comment by tohrxyz** [comment]
+1 
This is insanely annoying bug that I'm encountering frequently when I'm travelling around the crypto-events or conferences. I need to input in eur, it rejects it and then remember the sat amount and enter that in Sats (unit)

Please fix ASAP

**Comment by dpad85** [comment]
> Edit2: now I see that it's in release 2.0.2 which hasn't arrived to app store yet, but I'm looking forward to it. Thanks for your hard work!

The fix is actually only on Android, but not on iOS. We'll try to make a patch before the public release of the iOS splices version. In any case, thanks for reminding us of this issue!

**Comment by robbiehanson** [comment]
iOS fix will be available in the next version: 2.0.4
