### ISSUE TITLE
Satoshi I sent didn't receive 

### ISSUE THREAD

**Issue by NikolausStefan** [ACINQ/phoenix#392]
Dear Sirs, 

I sent 3 days ago 0.0018 btc, which I didn't receive on my phoenix wallet. 

Can you help me? 

![Screenshot_20230811_152405_com coinbase android](https://github.com/ACINQ/phoenix/assets/72549063/fffb0186-1e66-47f5-8a0d-6aa74f5e8431)
![Screenshot_20230811_152451_com android chrome](https://github.com/ACINQ/phoenix/assets/72549063/75e7ed84-6794-417d-a5d5-d2babbe01ff7)
![Screenshot_20230811_152541_com android chrome](https://github.com/ACINQ/phoenix/assets/72549063/77a26311-63cd-4ecd-8ddd-e772f3f64214)
![Screenshot_20230811_152425_com coinbase android](https://github.com/ACINQ/phoenix/assets/72549063/1b7ca606-2893-40bb-9ec1-41ff665e00e0)

**Comment by dpad85** [comment]
Closing this ticket because support is done by email.
