### ISSUE TITLE
App crashes when Tor is quickly turned on and off

### ISSUE THREAD

**Issue by MasterixCZ** [ACINQ/phoenix#396]
1. Click on Enable Tor button.
2. Immediately click on the button to turn Tor proxy off (when it's displaying "The Tor proxy is shutdown etc. etc.").
3. App crashes.

**Comment by t-bast** [comment]
This is probably linked to one of the bugs fixed by https://github.com/ACINQ/lightning-kmp/pull/512

**Comment by MasterixCZ** [comment]
I tried it now and it's fixed. Thanks
