### ISSUE TITLE
APK files missing in Releases page

### ISSUE THREAD

**Issue by cstenglein** [ACINQ/phoenix#398]
The last 1.x release (1.4.27) has a APK file attached on the Releases page: https://github.com/ACINQ/phoenix/releases/tag/android-legacy-v1.4.27

The current 2.x releases do not: https://github.com/ACINQ/phoenix/releases/tag/android-v2.0.1

Please add the apk files there as well, so users can install the app independently from app stores.

**Comment by Barnminer** [comment]
What is the deal on the APK. They forget to upload it or is it in the zip files?

**Comment by dpad85** [comment]
Hi, the apks for v2+ have not been uploaded yet because we want to roll out this version gradually (which we can do on Google Play but not with a public file). They will be uploaded in the coming days. Thanks for your patience.

**Comment by Barnminer** [comment]
Thanks for the response. I have not installed a previous version yet if In were to install then upgrade when available would I simply just download the new apk and run it or would anything else be necessary?

-------- Original Message --------

**Comment by cstenglein** [comment]
Thank you for the response @dpad85 

Can thus be closed IMO.

**Comment by dpad85** [comment]
The apk is available on the 2.0.1 release page.

> I have not installed a previous version yet if In were to install then upgrade when available would I simply just download the new apk and run it or would anything else be necessary?

If you never had a wallet, you can install the 2.0.1 version and create a new wallet. No migration needed in that case.
