### ISSUE TITLE
Wallet is unable to connect after upgrade

### ISSUE THREAD

**Issue by sha-265** [ACINQ/phoenix#400]
I updated my Phoenix wallet to the new version (2.0.2) and upgraded the wallet itself.

After the upgrade, Phoenix was unable to connect to the network, and saying no internet connection is available, although there is an internet connection in the android device.

I tried to uninstall Phoenix and restore the wallet, and now the app hangs on the "Checking legacy wallet..." screen forever.

**Comment by Avraham-K** [comment]
Same here

**Comment by dpad85** [comment]
What version of android are you running, and on what device? Are you using a VPN, or a public WiFi (like an hotel/airport/work)?

From this same device, on a browser, can you try accessing this url? https://acinq.co/phoenix/walletcontext.json

**Comment by sha-265** [comment]
I'm using Pixel 4a with Android 13. No VPN, no pubic WiFi.

> From this same device, on a browser, can you try accessing this url? https://acinq.co/phoenix/walletcontext.json

When I'm trying to access this url I get Cloudflare captcha page, and need to click the captcha to get the json file. So maybe this is the problem?

**Comment by dpad85** [comment]
Yes, this issue is related to that resource. We are fixing this in the next release. Thanks for your patience

**Comment by sha-265** [comment]
Fixed for me
