### ISSUE TITLE
LNURL Success action is missing from new version of Phoenix.

### ISSUE THREAD

**Issue by cmdruid** [ACINQ/phoenix#404]
Hello. Before the new update, Phoenix Wallet had `SuccessAction` implemented for LNURL invoices. This included URL links, which are used to complete purchases after a payment settles.

After the new update, the `SuccessAction` feature is completely missing, and now phoenix users cannot redeem their purchase after making an LNURL payment.

I'm not sure why this feature is suddenly missing, if it is a bug or intentional.

More details on LUD-09 `SuccessAction` can be found here:

https://github.com/lnurl/luds/blob/luds/09.md

As you can see, Phoenix is listed as having support. However with the new update it is now gone.

Any clarification would be appreciated, whether this is a bug or intentional. Thank you.

**Comment by dpad85** [comment]
Thanks for reporting this, that's a bug. We'll fix it asap.

**Comment by dpad85** [comment]
Fix will be available in next version 2.0.5.
