### ISSUE TITLE
Phoenix iOS v2 typo in splash page

### ISSUE THREAD

**Issue by notmandatory** [ACINQ/phoenix#411]
Platform: iOS
Version: 2.0.0

"Bump fess" should be "Bump fees" 🙂

![1C7220CC-3ED6-42DE-AE05-482D9FAA886E_1_102_o](https://github.com/ACINQ/phoenix/assets/4724730/240b6c1f-8b2e-4d7b-b212-906e2249bec6)

**Comment by robbiehanson** [comment]
Thank you ! :pray:
