### ISSUE TITLE
Phoenix / THNDR compatibility

### ISSUE THREAD

**Issue by abussutil** [ACINQ/phoenix#416]
Version: 2.0.5 on Android

On THNDR, I usually see Phoenix as an option to withdraw my prizes. The last payment I received on Phoenix was on Aug 25, 2023. 
 
Today, I tried again and it seems Phoenix is not recognized anymore as an option:
![THNDR-Phoenix](https://github.com/ACINQ/phoenix/assets/100695254/8def14c1-5674-42a0-9011-fd55db6798ac)

**Comment by dpad85** [comment]
Hi, that's an issue with the THNDR app, which seems to have delisted Phoenix for their withdrawals.
