### ISSUE TITLE
Is README and legacy app info up to date?

### ISSUE THREAD

**Issue by jooray** [ACINQ/phoenix#420]
The main README.md of this project says:

---

Phoenix is currently separated into two codebases:
- the legacy Android app, found in the `phoenix-legacy` folder, using our own Scala [eclair-core](https://github.com/ACINQ/eclair) library for Lightning. Instructions to build this app are provided [here](https://github.com/ACINQ/phoenix/blob/master/phoenix-legacy/BUILD.md)
- the iOS app found in the `phoenix-ios` folder, using our own Kotlin MultiPlatform [lightning-kmp](https://github.com/ACINQ/lightning-kmp) library for Lightning. Instructions to build this app are provided [here](https://github.com/ACINQ/phoenix/blob/master/BUILD.md)

The `phoenix-android` folder contains the new Android app that shares code with the iOS app and use lightning-kmp. This app is not ready yet. It will eventually replace the legacy Android app.

---

Is this still true? Phoenix-legacy is 1.4.x according to version information and play store has 2.x.

**Comment by dpad85** [comment]
No it's not correct, the README is not up-to-date, will fix.
