### ISSUE TITLE
Error: no channels available to send payment

### ISSUE THREAD

**Issue by knocte** [ACINQ/phoenix#435]
I've recently updated Phoenix (I can see in the main UI now "Congratulations! Your wallet has been updated"), but since then I cannot send payments, even if my channels seem healthy.

Please let me know how can I help debug this issue. (Note I was trying to pay an invoice for LnP2pBot escrow.) My current balance in the wallet is 4,042,444sat and my outgoing payment was around 259 USD.

**Comment by knocte** [comment]
After trying again a bit later, it has worked. Maybe because the layer1 tx for the last incoming payment had finally confirmed? Maybe the error message should state the channels unconfirmed status.

**Comment by dpad85** [comment]
Closing this issue. For future issues you have while making payments in phoenix, contact support by email: phoenix@acinq.co.

> Maybe because the layer1 tx for the last incoming payment had finally confirmed? 

Incoming deposits should not affect your channel's availability. Depending on the error you got when paying `LnP2pBot escrow`, it could simply be a liquidity issue on their side.
