### ISSUE TITLE
Sent sats from another wallet to phoenix just before updating

### ISSUE THREAD

**Issue by sheepbild** [ACINQ/phoenix#436]
Hello,
I wanted to bail out my phoenix wallet 2 days ago. I went to Phoenix on iPhone and sent to "onchain address". Since then, transaction has been broadcasted and validated, it now has more than 200 confirmations. Seeing that the payment was not arriving, I asked for help and was advised to update the application.

2 problems : 
- When I launch the app after the update, I can't upgrade my channels. I click on "get started" and nothing is happening. "Receive" and "Send" buttons are in red and I see "+ xx eur incoming" (the original balance of my account WITHOUT the onchain reception that I expect)

- I have a second Android phone connected to the wallet where I did not made the update of the app. Even here I still have not received the 217k sats of my onchain transaction.

I think the channel update fails because there is this 217k sats received onchain, but I can't see them anywhere, whether it's on the new or the old version.

TX ID : 94e9fd734c86498f61724314558985b1095ee56580d4e44c02faceed5b997330

**Comment by dpad85** [comment]
For issues with payments in Phoenix, please contact the support: phoenix@acinq.co
