### ISSUE TITLE
Payment between Phoenix Android wallets fail

### ISSUE THREAD

**Issue by yukibtc** [ACINQ/phoenix#437]
Hi, I'm experiencing an issue sending funds to another Phoenix wallet: Android <-> Android (v2.0.9).
The error received is: `payment attempts exhausted without success`.
The payment fail immediately, even with a very small amount (like 10 sat).

iOS <-> Android works well.

Trying to send/receive payments to/from other wallets works.

**Comment by dpad85** [comment]
Make sure that the receiving app is in the foreground. [Some Android devices will kill apps that are not visible](https://dontkillmyapp.com) and you'll have to whitelist phoenix.

Also note that incoming payments may be rejected by the receiving app if the fee is too high. The receiving app will show details in settings > notifications in that case. For example, a new app without any channel will not be able to receive 100 sat, as creating a new channel will typically cost in mining fee alone around 2000 sat, sometimes much more.
