### ISSUE TITLE
Payments always fail with custom Electrum server (Fulcrum)

### ISSUE THREAD

**Issue by jordan-bravo** [ACINQ/phoenix#443]
With default Electrum server settings, payments consistently succeed.  When changing to a custom Electrum (Fulcrum) server, Phoenix appears to sync successfully.  However, any payment made, no matter how small, will fail. 

The Electrum (Fulcrum) server works perfectly with other wallets and shows all signs of being configured properly.

OS: Android version 14
Phoenix version `2.0.10`

Screenshots:

![failed-payment](https://github.com/ACINQ/phoenix/assets/62706808/b26b7380-81f3-4a67-8465-b04d4dbbbfd2)
![failed-payment-details](https://github.com/ACINQ/phoenix/assets/62706808/e35609c0-12d2-4e42-91ad-58455e76efad)

**Comment by dpad85** [comment]
What blockheight do you have in settings > electrum server? Is there a public Fulcrum server we could connect to to reproduce this issue?

**Comment by jordan-bravo** [comment]
Prompted by your comment, I checked the blockheight and found it to be behind the current blockheight.  After investigating further, I discovered that `bitcoind` wasn't able to find any peers.  I simply had to restart the `tor` service and the `bitcoind` service, then peer connections were reestablished.  Once the blockchain was finished syncing to the current blockheight, I tested out a payment with Phoenix and it was successful.

So it definitely was not an issue with Phoenix.  Please excuse the erroneous bug report.  Thank you for your help.  I'm closing this issue as resolved.
