### ISSUE TITLE
[bug] No notifications, but still the (1) badge on app

### ISSUE THREAD

**Issue by Decryptu** [ACINQ/phoenix#451]
Hello, after receiving the last notification about wallet migration, the notification badge won't leave.

![image](https://github.com/ACINQ/phoenix/assets/90518536/e366d134-d15a-4eb5-9305-d83ef4b0df26)
![image](https://github.com/ACINQ/phoenix/assets/90518536/cf9de009-153f-4263-899d-0598a783f28d)

I tried to reboot the phone, my os is the latest, app version is the latest. iPhone 13 Pro, iOS 17.0.3,  App 2.0.6, nothing worked to make the notification badge disappear.

**Comment by dpad85** [comment]
The badge appears when there's an iOS system notification. Check in the iOS Notification Center for any missed messages. You can also make system notifications more prominent in iOS Settings > Apps > Phoenix > Notifications, and select the Banner options.

**Comment by Decryptu** [comment]
I think you misunderstood, it has been days since the notification badge on the phoenix wallet app wont leave, this notification was for the wallet upgrade thing on the last update, and now even after more than a week, multiple reboot, the notification badge is still here
