### ISSUE TITLE
Face-ID necessary, no Code possible 

### ISSUE THREAD

**Issue by notrelevant11** [ACINQ/phoenix#455]
After my TrueDepth Sensor of the iPhone is broken I‘m not able to access the Phoenix app anymore.
If I start the app it will use FaceID with „Please enable Face ID“ olthough I’ve deactivated FaceID systemwide.
There is no automatic use of the Apple Code like on most other apps.

thanks in advance

**Comment by robbiehanson** [comment]
A "passcode fallback" option has been added. It should be available in the next released version of Phoenix.
