### ISSUE TITLE
Buggy update process

V 1.4.27-93b82893 (66)

### ISSUE THREAD

**Issue by i5hi** [ACINQ/phoenix#462]
I have been using pheonix for months now. I wanted to recover my wallet on a new device and transfer funds to my channel.

I imported my wallet and then did the update that I was prompted to do. It then started the migration process and closed the channel. A new app then opened up. It didnt have my clowed channel funda. It showed me the address to fund the new channel. I sent funds there. I was notified about the tx at 0 conf....

Then the app just showed 'Opening Legacy Wallet..' and now I cannot access that new wallet anymore.

It seems like it created a new wallet since my old wallet only has funds from the migration (checked by recovering my onchain seed in another wallet.)

**Comment by i5hi** [comment]
After I clicked update again brought me back to the new app and now I see my funds. 

That was stressful...

**Comment by i5hi** [comment]
It still keeps jumping back and forth between the new and old app...

**Comment by dpad85** [comment]
It looks like you still have active channels on the legacy app, that's why you switch back & forth. In any case, please contact support (phoenix@acinq.co) for help, GitHub is intended for technical issues, thanks.
