### ISSUE TITLE
Phoenix doesn't allow choice in BIP21 with BOLT11 in deep link

### ISSUE THREAD

**Issue by NicolasDorier** [ACINQ/phoenix#466]
I use Phoenix (2.0.12) on Android, when I click on the button "Pay in Wallet" with a BIP21 having a `lightning=`, I am not presented with a choice as I would if I just scanned the QR Code.

You can check with the following, 

* Go on https://mainnet.demo.btcpayserver.org/apps/3Q3sWFpWkCEcsPoJnoB3k9x3qS3m/pos on mobile
* Enter 1500 JPY
* Click "Pay in Wallet"

Here a QR Code to open the app on mobile:

![image](https://github.com/ACINQ/phoenix/assets/3020646/8711597d-6f4e-4082-a0d4-2c0578506a80)

**What you see**: On-Chain payment without amount prefilled.
**What I am expecting**: Same experience as QR Code, ie, it should ask me to pay on lightning or on-chain, and prefill the sats amount.

**First question**: If on-chain payment is selected by default, why the sats amount isn't even prefilled.
**Second question**: on-chain payment shouldn't be selected at all, instead the app should give the choice to select lightning.

Link to: https://github.com/btcpayserver/btcpayserver/issues/5455

**Comment by dpad85** [comment]
Thanks for reporting this. It's a bug in the logic forwarding the bitcoin uri to the scanner, hence the amount not being filled in the payment screen, and the dialog to choose a between on-chain/off-chain being missing.

**Comment by dpad85** [comment]
This will be available in the next release. Thanks for your patience!
