### ISSUE TITLE
Testnet APK is using mainnet fees

### ISSUE THREAD

**Issue by bordalix** [ACINQ/phoenix#471]
While using https://acinq.co/pub/phoenix/phoenix-testnet-latest.apk the amount of estimated fees shown on channel management is 53,824 (~20.14 USD). These are mainnet fees, not testnet fees.

**Comment by dpad85** [comment]
Yes, that's on purpose, the testnet version is using mainnet fees to keep in touch with the real cost of transacting on-chain, even in development mode. Otherwise one could end up with wrong expectations (like thinking a swap typically costs 300 sat) and build use cases based on that.
