### ISSUE TITLE
Trying the testnet app: payment attempts exhausted without success

### ISSUE THREAD

**Issue by datgrog** [ACINQ/phoenix#473]
Hello,

I download the testnet version of the app and received 1M sat from L1 which the app convert to LN.
Then I made an invoice using my voltage lightening node (my node) into https://app.voltage.cloud/flow/ondemand just to emulate a use case in which the LN node (my node) was new with no channel or UTXOs. Flow service then generate a wrapped invoice.

Unfortunately Phoenix wallet when paying the wrapped invoice fails with "payment attempts exhausted without success" and I tried 8 times. Is there anything I can do ?

**Comment by dpad85** [comment]
This is probably a liquidity issue in between the testnet Phoenix LSP (`endurance`) and the Voltage testnet LSP. The testnet network is not as well maintained as the mainnet one. Can you try again with a smaller payment?

**Comment by datgrog** [comment]
Many thanks for your help. I tried with as few as 100 sats but still same error. The wrapped invoice ask for fees to cover the channel opening (10k sats) on top of my 100 sats but still too much apparently.
I guess you're right so now at least I have a better understanding about what is going on so thanks 👍

**Comment by dpad85** [comment]
> The wrapped invoice ask for fees to cover the channel opening (10k sats) on top of my 100 sats but still too much apparently.

I'm not familiar with the on-demand flow in Voltage, but it's likely they pay the channel opening fee out of the payment that are being forwarded. So if you try sending 300k sat this time, the amount should be high enough that they can collect the 10k fee ; then they'll be able to open a channel to your LN node, and you can receive the payment.

Closing this issue for now but feel free to re-open if there's an issue in phoenix.
