### ISSUE TITLE
Cannot connect wallet to Electrs 

### ISSUE THREAD

**Issue by pv8man** [ACINQ/phoenix#476]
Running Electrs on Umbrel, fully synced.

When I try to connect my server via "use a custom server" option using my Electrs TOR address (TorAddress:50001), it keeps saying "failed to connect: This address cannot be resolved".

TOR is enabled on phoenix and is successfully connecting to other random electrum servers, just not mine.

**Comment by dpad85** [comment]
If you are using an onion address, this will be fixed by #479.
