### ISSUE TITLE
Phoenix v2: recovered wallet but can't see my Sats

### ISSUE THREAD

**Issue by lularocha** [ACINQ/phoenix#495]
Using latest iOS.
- Phoenix v2 got stuck "checking peers"
- So I've deleted the app and reinstalled it
- Recovered the wallet with seed phrase
- But now the balance is showing Zero Sats
Can someone help me with this please?

**Comment by lularocha** [comment]
Solved

**Comment by dpad85** [comment]
No worries, good to see you find a solution. Note that for issues with payments, support is done by email (phoenix@acinq.co).
