### ISSUE TITLE
Phoenix Android v2.1.1 typo in Receive page

### ISSUE THREAD

**Issue by BitByBitByBitByBit** [ACINQ/phoenix#497]
The copy in the Lightning pop-up text box says "swipe to the right" but according to the UI it should be to the left.

![20231228_125145.jpg](https://github.com/ACINQ/phoenix/assets/122701291/ccec1cdd-0f0d-4368-aa79-30f78bf78b8a)

**Comment by dpad85** [comment]
Fixed with 7a9d48be, thanks.
