### ISSUE TITLE
Phoenix Android 2.1.1: Zero balance even though wallet has funds

### ISSUE THREAD

**Issue by sgsavu** [ACINQ/phoenix#498]
I have entered the seed into a sparrow desktop wallet and proceeded to send some funds to the wallet. The .../0/0 public address was used for this.
Looking at the wallet on sparrow and on the blockchain we can see that the transaction has been confirmed and it is being displayed accordingly.
However, on the phoenix mobile app this is not the case. It still says that I own 0 bitcoin.

Does the wallet only display lightning balance ? If so, I find it a bit confusing.

![image](https://github.com/ACINQ/phoenix/assets/45766423/e8cc527a-ffcb-4bdb-a4e1-807d9723294f)
![image](https://github.com/ACINQ/phoenix/assets/45766423/9c1700a7-a736-44bd-b373-ed0e8e52ffe2)
https://mempool.space/address/bc1qe6pmy87gnh757thxak3fgcmelamepxxvka7jhx

**Comment by dpad85** [comment]
Yes , Phoenix only displays your LN balance, see https://phoenix.acinq.co/faq#where-is-my-on-chain-balance. 

On-chain funds are ignored, except for funds deposited to the Bitcoin address displayed in the Receive screen, where we are using a [mechanism inspired by swap-in potentiam](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-January/003810.html) to make trustless 0-conf swaps to LN.
