### ISSUE TITLE
Tor (proxy) support

### ISSUE THREAD

**Issue by Kixunil** [ACINQ/phoenix#5]
Add a setting to use Tor. For greater UX, auto-detect Orbot being installed, test the connection and use it automatically if it works.

When setting up `.onion` addresses for Electrum server, use that as well.

**Comment by sstone** [comment]
We've added supports for socks5 proxies in eclair-core (see https://github.com/ACINQ/eclair/pull/1315)  which is the "Lightning engine" that powers all our apps including Phoenix, so the next version should be able to connect to `.onion` Electrum servers, and we're also testing ways of providing TOR support without having to rely on external dependencies.

Please note that you can already use eclair-mobile and phoenix with Orbot in VPN mode.
