### ISSUE TITLE
UX: Subtle Max Fee Warning -> Prominent Max Fee Suggestion

### ISSUE THREAD

**Issue by kilrau** [ACINQ/phoenix#507]
We are seeing not few failed swaps at Boltz that turned out to be due to user's too low `max fee amount` limit in their Phoenix application that blocked the splice-in. The default of 5000 sats is just not nearly enough these days.

![image](https://github.com/ACINQ/phoenix/assets/19181985/13a34768-4533-4980-a15a-7c24d2652594)

Since we are ususally sending these kind of screenshots to make users aware that there is such setting in the first place (literally everyone we talked to overlooked the warning), how about moving from this rather subtle warning to a more prominent even *screen blocking* suggestion to "raise max fee amount to X according to current estimates, otherwise this payment is likely to fail" to make splice-ins more likely to succeed? The fee estimate is even shown in the max fee amount menu, it's just most don't even get to that screen. It should be a one button tap to take over the fee limit suggestion.

![image](https://github.com/ACINQ/phoenix/assets/19181985/c2ff8b7d-95cf-44e9-a0aa-949a65df8528)

The user should be able to deny this max fee limit suggestion but then it's crystal clear at least that the payment for this invoice amount is likely to fail and folks don't end up in our support channels blaming us :v:

**Comment by dpad85** [comment]
This issue is fixed on Android with release 2.1.3, but not on iOS yet. I will update this ticket once iOS is ready.
