### ISSUE TITLE
 transactions are stuck in phoenix wallet. See photo

### ISSUE THREAD

**Issue by Wlmr1** [ACINQ/phoenix#510]
![IMG_0483](https://github.com/ACINQ/phoenix/assets/157431843/a77d8071-8e9a-4473-a324-f03243d7f536)

**Comment by Wlmr1** [comment]
It has been like that for 16 hours, it won’t clear

**Comment by dpad85** [comment]
Contact support by email: phoenix@acinq.co if you have issues with your wallet.
