### ISSUE TITLE
onchain deposit address reuse

### ISSUE THREAD

**Issue by MaxHillebrand** [ACINQ/phoenix#519]
Currently phoenix reuses addresses for the onchain swap deposit address.

This means that outside observers (and especially senders) can see how frequently and what amount was received by a user in the past and future.

Privacy and security would be improved by creating a new address for each deposit.

**Comment by t-bast** [comment]
This is something we're working on, but only makes sense when using taproot addresses, see https://github.com/ACINQ/phoenix/issues/403 and https://github.com/ACINQ/phoenix/pull/516

**Comment by MaxHillebrand** [comment]
Sorry for the duplicate, apparently I didn't search the repo thoroughly enough...

Amazing that you're already tackling the issue, and with taproot there should be even further script privacy improvements, that's great, thank you! 🖤

**Comment by dpad85** [comment]
With v2.2.0 released on iOS and Android, Phoenix now rotates the on-chain address (see https://acinq.co/blog/phoenix-swaproot for details and more).
