### ISSUE TITLE
Unable to receive any payment

### ISSUE THREAD

**Issue by MButcho** [ACINQ/phoenix#528]
I was using Phoenix for a while without any issues. Yesterday, receving any amount stopped working. I have 1 141 049 / 11 467 360 sats channel, it is showing as active but I doubt it. I tried sending 100, 100 and 500 000 sats from WoS, also tried to test receving from Binance, payment fails. The error in WoS is:
![image](https://github.com/ACINQ/phoenix/assets/41790777/c756bb18-a1cc-4bd4-bac4-d09c17651ffd)

I had LN node so I know how it works. It looks to me that the channel is down, although Phoenix shows state: Active

**Comment by dpad85** [comment]
Payments between wallet of satoshi/phoenix work fine currently, there are no known issues. Check this entry in the FAQ : https://phoenix.acinq.co/faq#receiving-or-sending-payments-keeps-failing-what-can-i-do. Some devices will disconnect apps that are put in the background, which will cause payment issues.

**Comment by MButcho** [comment]
> Payments between wallet of satoshi/phoenix work fine currently, there are no known issues. Check this entry in the FAQ : https://phoenix.acinq.co/faq#receiving-or-sending-payments-keeps-failing-what-can-i-do. Some devices will disconnect apps that are put in the background, which will cause payment issues.

I read the FAQ, nothing helps to receive payments. What should I do?

**Comment by MButcho** [comment]
> Payments between wallet of satoshi/phoenix work fine currently, there are no known issues. Check this entry in the FAQ : https://phoenix.acinq.co/faq#receiving-or-sending-payments-keeps-failing-what-can-i-do. Some devices will disconnect apps that are put in the background, which will cause payment issues.

Started to work today again, without any interaction from my side

**Comment by dpad85** [comment]
Thanks for updating this ticket. We fixed an issue with background payments on iOS, so you fell into the issue mentioned in the link in my previous comment.
