### ISSUE TITLE
Allow (local network / tor) electrum server without certificate

### ISSUE THREAD

**Issue by Sjors** [ACINQ/phoenix#534]
I run an [electrs](https://github.com/romanz/electrs) instance on a private network. Having to make a maintain a certificate for it is a bit of a pain. It would be nice if there was a way to opt out of needing a certificate.

At the same time I understand that you don't want to introduce a footgun. Perhaps the app could allow it for private address ranges like 192.168 (https://datatracker.ietf.org/doc/html/rfc1918)

You can probably also drop the requirement for onion addresses (maybe it already does, I haven't tried).

**Comment by dpad85** [comment]
> You can probably also drop the requirement for onion addresses

Yes that's what we do already.
We'll think about whitelisting local addresses, with a warning I think it should be fine, and it's easy to do.

**Comment by Sjors** [comment]
This has been working like a charm for a while now, now sure which version it was added.
