### ISSUE TITLE
Remove animated navigation on iOS

### ISSUE THREAD

**Issue by dpad85** [ACINQ/phoenix#552]
I think in general we should remove all animated navigation, and instead directly navigate to the correct screen:
- animated navigation take control away from the user (which feels weird) and waste time
- probably require complex code, which cause issues & maintenance

For example:

When tapping on a pending deposit amount in the Home screen, the app redirects to the "Swap-in wallet" view ; that part works fine.

But then, when tapping on "Configure fee settings", the app navigates (with an animation) to the Settings screen. Tapping on the Back button navigates to the Home screen, then to the Settings screen again.

**Comment by robbiehanson** [comment]
I agree. Note that this probably requires full adoption of [NavigationStack](https://developer.apple.com/documentation/swiftui/navigationstack), which is iOS 16+. Which means dropping support for iOS 15. With iOS 18 coming out soon, it's probably time...

**Comment by robbiehanson** [comment]
Done via #623
