### ISSUE TITLE
iCloud Seed Backup Error on iOS

### ISSUE THREAD

**Issue by gwo0d** [ACINQ/phoenix#566]
In the Phoenix app for iOS, if a wallet with its seed backed up to iCloud is reset, and another created afterwards, it becomes impossible to backup the new wallet's seed, with a generic CKRecord error provided in response. Having reviewed the code, I suspect the issue is within the phoenix-ios/phoenix-ios/sync/SyncSeedManager.swift file. However, my Swift proficiency and knowledge of Apple SDKs has limited my progress thus far.

Any help would be appreciated!

**Comment by milicodex** [comment]
I have the exact same issue as described by gwo0d. iPhone 12 Pro - iOS 17.5.1

**Comment by hcarrega** [comment]
just found this wallet today from silent.link and try to give te a try, i saw that error to sync seed on icloud

**Comment by makyurt** [comment]
Looks like this issue still exist. I use multiple Apple devices and iCloud backup would be great when restoring on a new device.

**Comment by dpad85** [comment]
Sorry for the delay, we have fixed the issue. There was a misconfiguration in the iCloud settings. No need to update the app, you should be good now. If not please reopen the ticket.
