### ISSUE TITLE
Bits UI is displayed wrong/bad.

### ISSUE THREAD

**Issue by pinkyjackgit** [ACINQ/phoenix#574]
The current "bits" option within phoenix uses a ",".

Shouldn't this be using a "."?

If so I've supplied 2 images which would help clean up the ui design for bits usage

![1 with dot](https://github.com/ACINQ/phoenix/assets/165532232/570574a8-f56d-4550-ac06-ffa9215a2afd)
![2 with btc logo](https://github.com/ACINQ/phoenix/assets/165532232/43501e38-721f-45be-87e0-2636e80d5566)

**Comment by dpad85** [comment]
What language/region are you using on your device?

**Comment by robbiehanson** [comment]
The formatting of these numbers are based on your configured language/region (i.e. in iOS settings).

So, for example:
- standard USA formatting would be: "505.85 bit"
- standard Colombia formatting would be: "505,85 bit"
