### ISSUE TITLE
Phoenix crash on loading window when I try to claim sats from thndr game.

### ISSUE THREAD

**Issue by bitcoinuser** [ACINQ/phoenix#58]
Phoenix crash on loading window when I try to claim sats from thndr game. See prints and log.

![photo_2020-04-14_19-49-19](https://user-images.githubusercontent.com/1178856/79281430-123f9e80-7e89-11ea-808e-a1aad73ee46d.jpg)

![photo_2020-04-14_19-49-25](https://user-images.githubusercontent.com/1178856/79281438-17045280-7e89-11ea-8777-37f6a6a1679e.jpg)

[phoenix.log](https://github.com/ACINQ/phoenix/files/4478162/phoenix.log)

**Comment by dpad85** [comment]
Thanks for reporting this, this issue has already been fixed and the release is on its way. It should be available in the coming days.

**Comment by bitcoinuser** [comment]
Ok, closing.

**Comment by dpad85** [comment]
I reopen this issue because it is useful to other users, as long the release is not yet available.

Note that this issue can be bypassed if you first launch the app independently, open the "Send" page, and then copy-paste the invoice/LNURL.

**Comment by dpad85** [comment]
Fixed with https://github.com/ACINQ/phoenix/releases/tag/v1.3.1
