### ISSUE TITLE
Prefer BIP353 over LNURL if found

### ISSUE THREAD

**Issue by Sjors** [ACINQ/phoenix#589]
Or at least, it would be nice to have this configurable.

Right now for `sjors@sprovoost.nl` it finds my NLURL instead of bolt12.

This was with iOs app version 2.3.0. It can pay to the (CLN generated) offer just fine if I paste it directly. 

BIP353 has better privacy properties for the sender, so in the long run it should be preferred. But it's still new.

**Comment by dpad85** [comment]
> This was with iOs app version 2.3.0.

You'll have to upgrade to version 2.3.1 -- the previous version can pay offers, but has no understanding of BIP353 and always tries to pay email-like address through the LNURL flow.

BIP353 is supporting on Android 2.3.3+ and iOS 2.3.1+, and indeed Phoenix will always try BIP353 first, and will only fallback to LNURL if BIP353 fails. Though we should also have an option (opt-in) somewhere to never fallback to LNURL.

**Comment by Sjors** [comment]
Ahh I tried too soon :-)

Will let you know if doesn't work as expected.
