### ISSUE TITLE
Typing "email" address support

### ISSUE THREAD

**Issue by Sjors** [ACINQ/phoenix#590]
Typing an email / lightning / bip353 address right in the app is often more convenient than having to scan or paste it. I find myself typing it in another app and then pasting it.

**Comment by Sjors** [comment]
(and it should probably track recipients so you can send them money again, but that's potentially much more involved)

**Comment by dpad85** [comment]
The "send" view is going to be reworked. It was designed around a bolt11 payment flow where most of the time you had to scan a QR code to do anything.

But now, with static payment instructions becoming more prevalent, that screen should be designed around a contacts/recent payments UI + a free form text input. There will still be a button somewhere to open the scanner but it should not be the default.

@robbiehanson that will be a good opportunity to rework the `ScanController` class, maybe remove the MVI pattern as well.

**Comment by notmandatory** [comment]
I've been playing with the "Contacts" feature and it would be nice to be able to add a `lno` address to my contact list using someone bip353 also.

**Comment by Sjors** [comment]
@notmandatory I think you can now save it when you send the first time.

**Comment by notmandatory** [comment]
@Sjors thanks for the tip! I tired it (iOS/v2.3.2) and when I manually input the bip-353 `lno` address I was given a little button to add that address to a new contact in my contacts. I also confirmed that if I manually enter the address for an existing contact that the payment screen detects that and shows me the contacts name on the confirm payments screen.

**Comment by robbiehanson** [comment]
Fixed via #629 & #643
