### ISSUE TITLE
App crashes when bolt 12 TX message is greater than 11 characters

### ISSUE THREAD

**Issue by HalFinneyIsMyHomeBoy** [ACINQ/phoenix#593]
- Try to pay a bolt 12 offer
- Attach message 12 characters or longer and app crashes
- Attach message 11 characters or shorter and payment is successful.

**Comment by dpad85** [comment]
I'm not able to reproduce this issue. What device are you using, with what OS version?

Also are you using special characters, e.g. anything outside the a-z 0-9 charset?

**Comment by HalFinneyIsMyHomeBoy** [comment]
Google Pixel 4a (running Graphene OS)
Phoenix version 2.3.3
Only sending numbers as a test

When I try to send to Matt Corallo's BIP353 address it crashes the app with 12 characters or more.
`lno1qsgr30k45jhvkfqxjqheaetacu4guyxvqttftvqu0f5sneckep3lkwdut7mmhhpcyjmlmnjn4hze8ed7pq88xqkxt2dcw5mlxhz644fms82f7k4ymfxs2ehhpjtxwxly0w5k8xdtlvpqyd8xzdq4tq8lgupnueshgydr330lc3j5kdcqh54gt7jdg9n68j4eqqeu7ts8uh0qxamee6ndj37tc6mzgejthvvjqj96p8dz2hrsh5z5n27qfk6svjz5pmkh0smq26k0j2j4q36xgq3r5qzet9kuhq4lydpen5mskxgjdvs5faqgv8pmj7cfd7ny84djksqpqk9ky6juc7fpezecxvg7sjx05dckyypnv9tmvfp6tkpehmtaqmvuupetxuzqf4t0azddjdcpasgw6hxuz9g`

However, when I send to D++'s BIP353 address, it works with 12 characters or more
`lno1zrxq8pjw7qjlm68mtp7e3yvxee4y5xrgjhhyf2fxhlphpckrvevh50u0qwvgtgks0yf528xwra0x7kerze27xhhws2w24e6txnx6g622wkwq6qszwuj258f0rh7ynjpz0gwxzvmlc3t3tqautjd5ktr3mwklqy64calqqvldcrxkj8az9lrgxdfs9jnefzz3lzn4pjhat6kp8rjcx0heev3zdtv6jza86kee7wca77agyyq0dz6uqdceqvll6uedk5e89j2zq0qpykzmpr0vac2l4q57mkj232szexcj9hgn5qqsnm5p9d6c66faxh6nf3wzjkc7k5`

**Comment by dpad85** [comment]
Thanks for the details. I can reproduce it with version 2.3.3. It's due to the onion payload exceeding the max size, and likely fixed by https://github.com/ACINQ/lightning-kmp/pull/686 (which will be shipped with the next version).

**Comment by HalFinneyIsMyHomeBoy** [comment]
Just successfully tested with version 2.3.4, this is fixed now.
