### ISSUE TITLE
Receiving via LNURL link is not working

### ISSUE THREAD

**Issue by mxicoderspl** [ACINQ/phoenix#596]
When we tried to scan the lnurl QR code from the Phoenix wallet's Recieve via lnurl's link, it always said "Error Processing Lnurl" We tried with another wallet and it is working there. 

In further debugging we found this error in our Lnd node:- "2024-07-19 14:20:40.164 [INF] CRTR: Payment 45cce64e133ce96c06d1ffd58b357c7a89a786109db0e94426d67fa8d1b4c682 failed: final_outcome=error, raw_err=InvalidOnionPayload(type=0, offset=0)@2"

So, please check this issue and let me know if needed further information.

**Comment by dpad85** [comment]
In Phoenix, are you able to reach the step where you have scanned the LNURL-withdraw code, reached the screen with the withdrawals details (including the amount), and triggered the withdrawal? If not, then check the LNURL withdraw code you've generated is valid with https://lightningdecoder.com/.

The error in your LND node seems related to a payment attempt. If it's related to the withdrawal, then it means you have successfully completed the lnurl-withdraw flow, and are now in the final payment step which is just a regular LN payment. If so, it's likely a problem in LND.
