### ISSUE TITLE
bip21uri with only a bolt12 lno address fails with unknown format error, but works if a bitcoin address is also included

### ISSUE THREAD

**Issue by remyers** [ACINQ/phoenix#598]
Phoenix version: 2.3.5 (android)

You can repo this error using https://satsto.me to resolve the URIs from the following bip353 addresses.

These bip353 addresses only resolve to a bolt12 static invoices and give the error: "This data uses an unknown format and cannot be processed."

bolt12@hrf.org ->
bitcoin:?lno=lno1zrxq8pjw7qjlm68mtp7e3yvxee4y5xrgjhhyf2fxhlphpckrvevh50u0qwnsha0tuuzrkh086l3lgsm3ezwvsnvc9tseezma2f3ptww2ngqq7qszwczwcquwd2gq3stnm6nvp6lme5gnyj8n396mk9rd0090vqqck4vsqvcydp6qkwzh32tz740gwwl70dllg3qukpuezep3amk2afmh3f50y99c2pqlupanxuvce6zewxcf7vhk255wqtlxahzqnvczydzqju6h3aa7cagwl4n6v54hqdg40nql7vt3v3uekqqsss3mtxynjw6cgtc9eznkchlmls

bolt12@yakshaver.org ->
bitcoin:?lno=lno1zrxq8pjw7qjlm68mtp7e3yvxee4y5xrgjhhyf2fxhlphpckrvevh50u0q0fpur5ezagkrszpfuyqvpw27kkyw9gnhl98c3w75hdadwz00jmqsqsr73zphy9alpauz89rs56m27cwyw3nwhhsdgj9nypa6ljxcnq5qf8sqve6fzk2nestscasjl5zct4a6kmeks9nxwjnchtllr8cv73z3c72gljcze9ejfz3856r0d3r0h29fr8rfwwmq2nfm9fjy2j380fnz65ulqhcdsgr8m2thr63ga44nnzj30e927gexqqs45znd4hfeha55kemx03zzr0gau

This address resolves to the same bolt12 address, but also resolves to a taproot address and correctly brings up the option to select either a bolt12 or on-chain address:

remyers@yakshaver.org -> 
bitcoin:bc1phr0em0k5hn0elzkdetmn0dxaluv73hwj3s8t63sgt8f7uhm5dhrqc20jau?lno=lno1zrxq8pjw7qjlm68mtp7e3yvxee4y5xrgjhhyf2fxhlphpckrvevh50u0q0fpur5ezagkrszpfuyqvpw27kkyw9gnhl98c3w75hdadwz00jmqsqsr73zphy9alpauz89rs56m27cwyw3nwhhsdgj9nypa6ljxcnq5qf8sqve6fzk2nestscasjl5zct4a6kmeks9nxwjnchtllr8cv73z3c72gljcze9ejfz3856r0d3r0h29fr8rfwwmq2nfm9fjy2j380fnz65ulqhcdsgr8m2thr63ga44nnzj30e927gexqqs45znd4hfeha55kemx03zzr0gau

This address resolves only to an on-chain address and properly goes directly to the payment dialog:
taproot@yakshaver.org ->
bitcoin:bc1phr0em0k5hn0elzkdetmn0dxaluv73hwj3s8t63sgt8f7uhm5dhrqc20jau

**Comment by dpad85** [comment]
Thanks for reporting this issue, will be fixed in the next release.
