### ISSUE TITLE
Lightning address no longer working for certain domains

### ISSUE THREAD

**Issue by TKone7** [ACINQ/phoenix#599]
## Issue
I noticed that since BIP-353 is implemented, some Lightning Addresses do no longer work.

## Reproduce
You can easily reproduce this:
- use latest release on Android
- send to any `<user>@getalby.com` Lightning Address
- you will get the error: Name `<user>` is not found on "getalby.com"

(other domains are most likely affected too)

This error code is thrown in the new `resolveBip353Offer` method. I see that there is a [condition](https://github.com/ACINQ/phoenix/blob/e73fb0e5aba1e890d141e6433d810ad7ab1f8047/phoenix-shared/src/commonMain/kotlin/fr.acinq.phoenix/controllers/payments/ScanController.kt#L579) to abort the `resolveBip353Offer` method without an error and proceed with the Lightning Address protocol. However, you rely on the status to be `null` or `>0`.

When run against the getalby domain [this results](https://dns.google/resolve?name=me.user._bitcoin-payment.getalby.com&type=TXT) in an answer without any error (`Status: 0`) but the expected record is not part of the answer.

**Comment by dpad85** [comment]
Thanks for reporting this issue, will fix. This is a regression from latest Android version where I wanted to have better errors for Bip353, but we should be more lenient and fallback to LNURL more easily. Also we need to extract this `resolveBip353Offer` method from the controller and make it testable.
