### ISSUE TITLE
Receiving over LN seems to be unreliable

### ISSUE THREAD

**Issue by Kixunil** [ACINQ/phoenix#6]
As reported by AndrejCibik on Twitter and also experienced by me, receiving over LN with pay to open seems to not always work.

Steps to reproduce:

* Create a new wallet
* Create an invoice and share with other wallet
* Pay the invoice from other wallet
* See that the dialog about setup fee isn't showing up
* Restart Phoenix
* The dialog shows up

Disclaimer: this could be slow connection in theory, but it's unlikely. I have very reliable connections (Internet and LN) and Andrej reported the same issue, trying several different wallets and LSPs.

**Comment by dpad85** [comment]
This issue is probably related to battery saving by some devices, where moving an app to the background seem to kill the connection for the app. Solution (as mentioned by @btcontract) could be to use a `ForegroundService` to keep the connection active (however a notification would be shown).

**Comment by andronoob** [comment]
>however a notification would be shown

As long as receiving over LN requires the payee to keep online, I think such notification should be an useful feature, instead of a bug.
