### ISSUE TITLE
[Feature request] Allow users to create contact from incoming payment

### ISSUE THREAD

**Issue by rabbitholiness** [ACINQ/phoenix#612]
I love the contacts feature. However, it would be great to be able to create a new contact from an incoming payment. Maybe this is only possible if the sender has the "Trusted contact" option enabled. But it would be nice.

**Comment by dpad85** [comment]
That's not possible at least not in the way contacts work, so I'm closing this issue for now.

A contact is linked to a bolt12 offer, and when you receive a payment, you do not get the offer of the sender (just a payer-key, and the way this key is linked to a contact is going to change, see https://delvingbitcoin.org/t/bolt-12-trusted-contacts/1046/4 and https://github.com/lightning/blips/pull/42)
