### ISSUE TITLE
Phoenix to Phoenix Wallet payment fails with error

### ISSUE THREAD

**Issue by ArbenKarb** [ACINQ/phoenix#62]
Worked when sending 4'000 sats, failed when receiving 1'337 sats and 1'000 sats

![image](https://user-images.githubusercontent.com/31412198/80203970-50c31f00-8628-11ea-8a47-ae1e347f66a7.png)

**Comment by dpad85** [comment]
This error happens when the app receiving the payment is not online, maybe because it was started but in background, or because the app was not started. We are working on a solution to notify the user when a payment is incoming his way and the app is not online.
