### ISSUE TITLE
use of external phoenixd server

### ISSUE THREAD

**Issue by github-tijlxyz** [ACINQ/phoenix#626]
It would be great if you can host your on phoenixd server and then connect the mobile app as just a UI for your own phoenixd server. 
There are several advantages:
 - better battery life: No need for background tasks on mobile, and easier notifications
 - being able to use the phoenixd api for advanced usecases, and the mobile app at the same time. with the same wallet.

**Comment by dpad85** [comment]
The advantages you mention are significant, but they are in contradiction to the main goal of this specific Phoenix Wallet project, which is to make Lightning as easy as possible for an everyday user. That is, have a standalone app that runs on mobile, with no remote server configuration.

A good solution for your use case could be to integrate phoenixd in existing Lightning node management tools, which are usually web-based, and could be used as a wallet.
