### ISSUE TITLE
Database is not compatible with this version of eclair

### ISSUE THREAD

**Issue by foxhaunt** [ACINQ/phoenix#638]
I use the APK version for android. Two days ago I started the application without any problem. Now when I start and after unlocking with my fingerprint I get this error and there is no way to access the app. I have updated to the latest version and I still get the same error.

**Comment by dpad85** [comment]
This is an old error that happens on legacy versions of the app (v1.x) that were using old channels format (and all these legacy channels have now been closed). Can you contact phoenix@acinq.co ? it will be easier to debug your issue that way.

**Comment by foxhaunt** [comment]
I use the APK version for android. Two days ago I started the application without any problem. Now when I start and after unlocking with my fingerprint I get this error and there is no way to access the app. I have updated to the latest version and I still get the same error.

I've just send an email to phoenix@acinq.co

Thanks.
