### ISSUE TITLE
crash when tap on "payment options" on android

### ISSUE THREAD

**Issue by pony-montana** [ACINQ/phoenix#655]
Hi, the issue is present from the 2.4.3 update on grapheneos without gms.
To reproduce, I simply open the app, click on "payment options" and it immediately crashes 100% of the times.

**Comment by milli** [comment]
This is happening to me also, Android 14 on Samsung (One UI version 6.1).  Same steps to reproduce.  I also cleared the app cache and it still crashes when clicking on Payment Options in Settings.

**Comment by dpad85** [comment]
Thank you for reporting this issue. Please update to version 2.4.4 it should be fixed.
