### ISSUE TITLE
Bug when trying to receive by copying full URI with offer

### ISSUE THREAD

**Issue by mattcrv** [ACINQ/phoenix#656]
When copying the full URI, I'm getting `bitcoin:?lno=QRCodeValue(original: "lno...", rendered: "lno...")` instead of `bitcoin:?lno=lno...`. Running Phoenix 2.4.3 on iOS 18.2.

![phoenix](https://github.com/user-attachments/assets/00aed70a-5168-4f16-806b-587239d7bab6)

**Comment by dpad85** [comment]
Thanks for reporting this issue, it should be fixed in the next release.
