### ISSUE TITLE
closing channels and losing all funds after restoring/transfer

### ISSUE THREAD

**Issue by jeff890729** [ACINQ/phoenix#69]
all my channels are suddenly closed
please I need a serius support because I have installed Electrum desktop but since 8 days my funds there no there, 
how can Phoenix app no have a serius support? that makes me think that anything is wrong and the app is not serius
1. support on telegram, what ist that is full of scamers and then contact me some one that want to still my seed
I have lost 5000 euros and no body cares

**Comment by pm47** [comment]
Support happened offband, user has recovered his funds.
