### ISSUE TITLE
Integrate a 2fa method to encrypt backup seed and transactions on Google Drive or ICloud

### ISSUE THREAD

**Issue by bitcoinuser** [ACINQ/phoenix#71]
Hi,

Will be great if Phoenix integrate a 2fa method to encrypt backup seed and transactions on Google Drive or Icloud. See this: https://github.com/photon-sdk/photon-lib

**Comment by bitcoinuser** [comment]
See this too: https://github.com/photon-sdk/photon-lib/issues/5

**Comment by bitcoinuser** [comment]
See in action: https://www.youtube.com/watch?v=N1c_AJg2jkY&feature=youtu.be&t=13m16s

**Comment by robbiehanson** [comment]
I apologize for the **super late** response.

> The encrypted backup is stored on the user's cloud storage account.
> The encryption key will be stored on your app's key server.

I don't see us implementing this anytime soon. Phoenix is a non-custodial wallet, and the focus is on minimizing trust. This would increase trust, as the app service (the company running the key server) would now be able to blackmail users who need to restore their wallet. (e.g. If you want access to your wallet with $1000, then please send us $10.)

Obviously we wouldn't do this (we'd go out of business overnight). But the goal is "can't be evil", and not "don't be evil".

I think this brings up an interesting conversation though: How does 2FA fit with bitcoin ?

> [A 2FA] scheme may include:
> 
> * Something the user has: Any physical object in the possession of the user, such as a security token, a bank card, a key, etc.
> * Something the user knows: Certain knowledge only known to the user, such as a password, PIN, PUK, etc.
> * Something the user is: Some physical characteristic of the user (biometrics, such as a fingerprint, eye iris, voice, typing speed, pattern in key press intervals, etc.)

Bitcoin, being completely decentralized, means there's no centralized authority to verify something like a bank card or fingerprint. However, the user is free to build their backup solution on top of other services that already provide these measures.
