### ISSUE TITLE
Receiving via LN doesn't work

### ISSUE THREAD

**Issue by roth-a** [ACINQ/phoenix#8]
Receiving without any channels returns the error (on sender side):

![screen](https://user-images.githubusercontent.com/1935665/70860727-aaeaff80-1f25-11ea-927e-14555f1218f6.jpg)

**Comment by roth-a** [comment]
Perhaps it is a duplicate of https://github.com/ACINQ/phoenix/issues/6  ?

**Comment by dpad85** [comment]
Yes there's a good chance that's the same bug. The message displayed here is generic, and means that the sender could not find a path to the receiver. Lack of inbound capacity was one of the main cause of it, but Phoenix does not have this problem thanks to the pay-to-open feature. However Phoenix still needs a connection.

Closing for now, you can reopen if you think that it's a different problem.
