### ISSUE TITLE
[REQ] Testnet version APK build on next release

### ISSUE THREAD

**Issue by brianddk** [ACINQ/phoenix#93]
Since ACINQ is already running a Testnet LN node for Eclair, could you consider having a Testnet version of Pheonix that uses it as well.  I realize you may not duplicate the swap-in / swap-out, but it would be nice to have a testnet version to kick around.  I'm hesitant to through a few hundred of BTC into a new LN wallet I haven't test-driven.  With the current mainnet network conjestion, even open / swap / close operations will cost non-trival amounts of sat.

**Comment by t-bast** [comment]
It's already possible to use Phoenix on testnet (we do it extensively), but it's true that we don't publish the built package.
Right now you can build from source yourself (the master branch builds for testnet).
We could publish built artifacts on github to allow easier testing, I'll let @dpad85 chime in on that.

**Comment by dpad85** [comment]
It would be nice to have an automated build for testnet, based on master. I'll look into that.

**Comment by brianddk** [comment]
@dpad85 Very cool.  Thx for adding.

For future readers, here's a hard link to actions triggered by a push on master

* [Actions: push on master](https://github.com/ACINQ/phoenix/actions?query=event%3Apush+branch%3Amaster)
