### ISSUE TITLE
Unable to pay invoices since a few days

### ISSUE THREAD

**Issue by giacomozucco** [ACINQ/phoenix#95]
I have a BTCPayServer shop I'm testing. I routinely pay LN invoices to it from many clients (including C-lightning, LND, Eclaire on Android, Phoenix on Android) with no problems.

About 6 days ago, trying to pay a ~$50 invoice from Phoenix resulted in the following error messages:
"PAYMENT FAILED. NO MONEY HAS BEEN SENT."
"payment fee was below the minimum required by the trampoline node"

The attempt failed 5 times (with 5 different invoices), but I dismissed the problem as likely temporary and moved to other clients.

Today I tried again and I still have the same error. I tried with the usual ~$50 payments but then, assuming it could be an amount problem, also with half the value.

I don't see any occurrence of the "payment fee was below the minimum required by the trampoline node" text message in other issues. The reference to the trampoline node, in particular, is a new one for me, across all clients.

The mobile wallet has enough funds in outbound liquidity. 

I can't parse the logs well enough to insulate the relevant information you may need excluding other sensitive stuff (there are several occurrences of "(failure=TrampolineFeeInsufficient)"), but I can easily share in private the complete logs of the last attempts.

**Comment by t-bast** [comment]
The error message is misleading and will be fixed in a next release, what this means is that we couldn't find a route from the ACINQ node to the final destination (your BTCPayServer instance).

Either there are no routes available, or they don't have enough liquidity to forward these payments.
Ideally, if you can ensure that there are channels between ACINQ and your node, with liquidity on the ACINQ side, this should work fine. If you provide us with the id of your node we can also open channels to you when we have available liquidity.

**Comment by giacomozucco** [comment]
Thanks for the fast reply. Happy we found a misleading error message to fix, but it's still a bit strange: I can still easily make payments of that entity to my BTCPayServer instance (which has got still 3,975,812 sats inbound capacity) from other clients (including Eclaire). Probably the liquidity bottleneck is in the route in-between. Thanks for proposing to open a channel with me directly, that should reasonably fix it. I past info here (not a secret channel anyway, also the alias is quite explicit ;) ).
029c1f31132d20d8242a75d09cc96a77fbe88026acf292c63714835b2b6c42eb1a@aw6yvwbugtvygajg26u7czhltkwvplegfyh2ag4frdsekiemy4epowad.onion:9735

**Comment by t-bast** [comment]
Thanks, it seems you have only one channel with the ACINQ node, if that one doesn't have inbound capacity and our node doesn't have enough outbound capacity going through the other nodes you're connected to, that's why the error happens.

**Comment by pm47** [comment]
> if that one doesn't have inbound capacity [...] that's why the error happens

This is precisely the problem
```
$ ./eclair-cli -s channels --nodeId=029c1f31132d20d8242a75d09cc96a77fbe88026acf292c63714835b2b6c42eb1a
[
  {
    "nodeId": "029c1f31132d20d8242a75d09cc96a77fbe88026acf292c63714835b2b6c42eb1a",
    "shortChannelId": "642974x1729x0",
    "channelId": "a73b6ada4338d2123f68fe2cfa74d9d1aacc4c06cd8fc706f48bbdf00f719660",
    "state": "NORMAL",
    "balanceSat": 0,
    "capacitySat": 1000000,
    "channelPoint": "6096710ff0bd8bf406c78fcd064cccaad1d974fa2cfe683f12d23843da6a3ba7:0"
  }
]
```

We can't open an additional channel because you are using c-lightning which doesn't allow multiple channels between same peers. A quick fix would be for you to send funds from your c-lightning node to your phoenix wallet, that would rebalance this channel.

**Comment by giacomozucco** [comment]
Thank you very much. I assumed other channels may route payments around this one, but now the issue is solved (just paying my phoenix from the server). Looking forward for the next release.
