### ISSUE TITLE
Cant pay an invoice created with LND on mainnet

### ISSUE THREAD

**Issue by enorrmann** [ACINQ/phoenix#97]
If I try to scan the code or paste it manually it shows invalid data
I generated the invoice via 
lnd addinvoice 120
LN v0.11.0-beta

Invoice
lnbc1200n1p054grypp5vhjgmnjfuzn2cwcxm8wnhwj5hk0nly87q374y5m90e36nvludn2qdqqcqzpgsp5se7ve8pym9h06uvp638ehg88edn70qfk6pw3a9j0h7jq3mt3gyhq9qy9qsqsmdrqux8f5lrs2myjj

**Comment by dpad85** [comment]
Hi, could you add the invoice to the issue?

**Comment by enorrmann** [comment]
Sure!
lnbc1200n1p054grypp5vhjgmnjfuzn2cwcxm8wnhwj5hk0nly87q374y5m90e36nvludn2qdqqcqzpgsp5se7ve8pym9h06uvp638ehg88edn70qfk6pw3a9j0h7jq3mt3gyhq9qy9qsqsmdrqux8f5lrs2myjj

**Comment by enorrmann** [comment]
I found the issue.. my transmission method was truncating the invoice .. sorry for the inconvenience
