### ISSUE TITLE
Payment fee was below the minimum required by the trampoline node

### ISSUE THREAD

**Issue by enorrmann** [ACINQ/phoenix#98]
invoices

lnbc120n1p05e5jdpp5ahvlf0l0cvcppddh74vae9jqpwx0gawklellujfzzvs2nzuw2nysdqqcqzpgsp5uwc4gxwnermrj67wydjwvm35tptsnp23ve0eacw25wz2q9lpe0eq9qy9qsqxtq94kuhenztp2gnvelzuepaafx2u8da7cl3p5zkxwja2mghc2q8gkhlck0eg0r67az73hr77ydf8ug9kw4a69gad8wqz8km88aq36qp0pfj9m

lnbc20u1p05e55lpp5ax0935k90p9vqc45ak72qcldgcs0xcp6m22ayj78rgsffppftzhsdqqcqzpgsp5hph6235554tpdnnxt9d4cul52mnljultwecsn8uxus2msyh72kwq9qy9qsqgqr6nfuccskg7qm9y3maysg4sg5cdxkt32us2l0gf6dv5tvqxk2ymqqslkxf0488xnqqe2zwagxh7yxfsvthtfpk0ssdve9nmgym9xgqljr2ry

both generated with LND .. is there a way to "raise" those fees to route the payment ?

**Comment by dpad85** [comment]
This error is confusing - it's thrown when the trampoline node cannot find a path to the payee. The maximum possible fee is actually high enough that it should not prevent a reasonable route from being used.

In most cases, this error simply means that there is no route to the payee. Bumping the fees would not help. Maybe channels to this node are not balanced, or do not have enough liquidity?

So in most cases this error is misleading and should be `Route not found`.

**Comment by ponli137** [comment]
I have gotten this error repeatedly in the last days when trying to send LBTC to a General Bytes ATM in Prague that I often use for withdrawing cash. 

So do I understand it correctly that the operator of the ATM has unbalanced LN channels and I should contact them to get it sorted? It has nothing to do with the fee that Phoenix wallet tries being to low, which the error message seems to indicate.

![Screenshot_20200909-203826_1](https://user-images.githubusercontent.com/33752947/92639916-c9c3ca00-f2dc-11ea-96f8-3db313248102.png)

![Screenshot_20200909-203931_1](https://user-images.githubusercontent.com/33752947/92639949-d7794f80-f2dc-11ea-93ce-f73e691a6e8f.png)

![Screenshot_20200909-204025_1](https://user-images.githubusercontent.com/33752947/92639980-e233e480-f2dc-11ea-964a-9d7597b231b1.png)

**Comment by t-bast** [comment]
@ponli137 exactly, the issue is that we can't find routes to the ATM node (ATMs are usually a one-way street, payments always go in one direction, so they have to rebalance regularly).
If you contact them and ask us to fix their incoming liquidity with the ACINQ node, it should go back to normal.
And as stated before, we'll change the error message in a next release to be more accurate.
