### ISSUE TITLE
Add option to hide balance and transaction history from main screen

### ISSUE THREAD

**Issue by pyskell** [ACINQ/phoenix#99]
While it's convenient to see it's also awkward to show your balance and transaction history when you're paying for something.

Compare to Venmo which doesn't show your balance on the main screen or CashApp which has it in relatively small text in the corner.

**Comment by bitcoinuser** [comment]
I think this was already fixed.

**Comment by dpad85** [comment]
Yep, this issue has been fixed by https://github.com/ACINQ/phoenix/commit/386c56dafe82e89a87a323169344fe22ee10fb19
